### ISSUE TITLE
Unable to delete ES 5 data. 

### ISSUE THREAD

**Issue by Sc0th** [StamusNetworks/scirius#104]
When I attempt to clear the elasticsearch data via the settings menu returns the following error.

'Clearing failed: TransportError(400, u'illegal_argument_exception', u'request [/_stats/_search] contains unrecognized metric: [_search] -> did you mean [search]?')'

Sirius version 1.2.1

**Comment by brandonmreeves** [comment]
Other than this issue it looks like the build with SELKS 4 is ready to go.

**Comment by brandonmreeves** [comment]
@pevma any update on this issue?

**Comment by pevma** [comment]
Fixed and available in the SELKS4 repos as a package as well.
