### ISSUE TITLE
Unable add source

### ISSUE THREAD

**Issue by esmelnikov** [StamusNetworks/scirius#106]
Hello!
After removing the source of "ETOpen Ruleset" due to errors:
SC_ERR_UNKNOWN_DECODE_EVENT: unknown decode event "decoder.ipv4.frag_too_large"
     SC_ERR_INVALID_SIGNATURE: error parsing signature "alert pkthdr any any -> any any (msg:" SURICATA FRAG IPv4 Packet size too large "; decode-event: ipv4.frag_too_large; sid: 2200069; rev: 1;)"
     SC_ERR_UNKNOWN_DECODE_EVENT: unknown decode event "decoder.ipv6.frag_too_large"
     SC_ERR_INVALID_SIGNATURE: error parsing signature "alert pkthdr any any -> any any (msg:" SURICATA FRAG IPv6 Packet size too large "; decode-event: ipv6.frag_too_large; sid: 2200071; rev: 1;)"

I'm trying to add this source again, but I get the following error:

![add sourse error](https://cloud.githubusercontent.com/assets/26947034/25562184/2478a942-2d98-11e7-8635-54d608379f24.PNG)

How to fix the error?

**Comment by stamus** [comment]
> On 30 Apr 2017, at 09:30, Eduard <notifications@github.com> wrote:
> 
> Hello!
> After removing the source of "ETOpen Ruleset" due to errors:
> SC_ERR_UNKNOWN_DECODE_EVENT: unknown decode event "decoder.ipv4.frag_too_large"
>      SC_ERR_INVALID_SIGNATURE: error parsing signature "alert pkthdr any any -> any any (msg:" SURICATA FRAG IPv4 Packet size too large "; decode-event: ipv4.frag_too_large; sid: 2200069; rev: 1;)"
>      SC_ERR_UNKNOWN_DECODE_EVENT: unknown decode event "decoder.ipv6.frag_too_large"
>      SC_ERR_INVALID_SIGNATURE: error parsing signature "alert pkthdr any any -> any any (msg:" SURICATA FRAG IPv6 Packet size too large "; decode-event: ipv6.frag_too_large; sid: 2200071; rev: 1;)"
> 
> I'm trying to add this source again, but I get the following error:
> 
> 
> 
> How to fix the error?
> 

Does the ETOpen ruleset page open from your browser ? It looks like may have been temporarily down ...

**Comment by esmelnikov** [comment]
The source "ETOpen Ruleset" was available in the browser, but it still could not be updated. If you remove the source before upgrading to SELKS 4, then there is no problem with the subsequent addition.

**Comment by pevma** [comment]
You can still remove it and add it in after the SELKS 4 upgrade correct?

**Comment by esmelnikov** [comment]
Yes, I confirm that I can delete and add a source after the above actions, the request can be closed.

**Comment by pevma** [comment]
Thank you for the feedback!
