### ISSUE TITLE
Status Red of Elasticsearch 

### ISSUE THREAD

**Issue by ReachInfinity** [StamusNetworks/scirius#108]
Hello it's my first post, I have install Scirius, I have configuring, it recognizes my node ES but ES is red.

This my configuration for ES and Kibana : 
```
USE_ELASTICSEARCH = True
#ELASTICSEARCH_ADDRESS = "127.0.0.1:9200"
ELASTICSEARCH_ADDRESS = "X.X.X.X:9200"
# You can use a star to avoid timestamping expansion for example 'logstash-*'
ELASTICSEARCH_LOGSTASH_INDEX = "logstash-*"
# You can change following value if you have different indexes for stats and alerts
ELASTICSEARCH_LOGSTASH_ALERT_INDEX = ELASTICSEARCH_LOGSTASH_INDEX
# use hourly, daily to indicate the logstash index building recurrence
ELASTICSEARCH_LOGSTASH_TIMESTAMPING = "daily"
# version of Elasticsearch
ELASTICSEARCH_VERSION = 5
# Extension used for complete field (usually "raw" or "keyword")
ELASTICSEARCH_KEYWORD = "raw"
# Hostname field (usually "hostname" or "host")
ELASTICSEARCH_HOSTNAME = "DEBIAN"

# Kibana
USE_KIBANA = True
# Use django as a reverse proxy for kibana request
# This will allow you to use scirius authentication to control
# access to Kibana
KIBANA_PROXY = False
# Kibana URL
KIBANA_URL = "https://X.X.X.X:5601"
# Kibana index name
KIBANA_INDEX = ".kibana"
# Kibana version
KIBANA_VERSION=5
# Number of dashboards to display
KIBANA_DASHBOARDS_COUNT = 20
# Path to Kibana's dashboards installation
KIBANA_DASHBOARDS_PATH = '/opt/kibana-dashboards/'
```

**Comment by regit** [comment]
ELASTICSEARCH_HOSTNAME is really to be choosen between hostname or host: check an event in Kibana to see if you have a host= or hostname= in it.

**Comment by ReachInfinity** [comment]
I have verify hostname and it's correct.

**Comment by regit** [comment]
@ReachInfinity it is the name of the key in ES events not the name of your host.

**Comment by ReachInfinity** [comment]
I have search the name of the key in ES events but I don't find. How I can find it the key ?

**Comment by regit** [comment]
Here is an event seen in Kibana:
![screenshot from 2017-05-22 12-41-47](https://cloud.githubusercontent.com/assets/308616/26304572/3c0dab88-3eec-11e7-9915-46facbbf1f8f.png)

The key that is used and must be set in scirius setting is `host`

**Comment by ReachInfinity** [comment]
Ok then my host is a IP address. But the problem persists, do you have any other leads?

**Comment by ReachInfinity** [comment]
Sorry I translated your answers well and now I understand much better. Thank you again for the answers.
