### ISSUE TITLE
Сan not activate the Commented Rules

### ISSUE THREAD

**Issue by esmelnikov** [StamusNetworks/scirius#114]
I use SELKS installed from the SELKS-4.0rc1-desktop.iso image. After installing worked fine. 
After the system the updated use script "/opt/selks/Scripts/Setup/selks-upgrade_stamus.sh", the following problems with the Scirius web interface appeared: After clicking on the link **_Action_** -> **_Toggle availability_** rule is not activated and its state does not change, that is, no additional items appear in the "Action" menu. The rule remains in the "Commented Rules" list.

**Comment by esmelnikov** [comment]
There is additional information on this issue. After a clean installation of SELKS 4, the _**Toggle availability**_ link for the commented rules works fine. Immediately after installing Java using the `/opt/selks/Scripts/Java/setup-oracle-java_stamus.sh` script , the _**Toggle availability**_ link stops working.

**Comment by pevma** [comment]
Interesting - is it the same after you restart Scirius - ``/usr/bin/supervisorctl restart scirius`` ?

**Comment by esmelnikov** [comment]
Checked, the problem remains.

**Comment by pevma** [comment]
One last check/confirmation please -  if you switch the default JAVA back to the original one - `` update-alternatives --config java`` would it be of any change?

**Comment by esmelnikov** [comment]
After switching to default Java nothing has changed.

**Comment by pevma** [comment]
Ok thanks for checking.
It seems not Java related in that respect then.

**Comment by regit** [comment]
OK. So there was a bug in the generated html preventing `toggle availability` to work. 51f7bb1062d4f823e9a18ba6c68c7f33cbad8a39 is fixing the issue.

**Comment by regit** [comment]
Closing as it is in 1.2.5 release.
