### ISSUE TITLE
Name doesnt Change on About Page

### ISSUE THREAD

**Issue by brandonmreeves** [StamusNetworks/scirius#120]
On the about page, the prior version of SELKS shows Suricata on (hostname). Now, no matter what the hostname is or what I can it to in Scirius, it always show Suricata on SELKS. Not sure if this is the intended output as it changed from the prior version

![screenshot from 2017-10-04 16-33-16](https://user-images.githubusercontent.com/21183397/31200824-f5d0303c-a921-11e7-814e-549a326874ec.png)

**Comment by pevma** [comment]
What was the change ?

> -- 
> Regards,
> Peter Manev

**Comment by regit** [comment]
No feedback, closing.
