### ISSUE TITLE
Scirius does only detects removed rules and not added over HTTP download

### ISSUE THREAD

**Issue by Tomasuh** [StamusNetworks/scirius#121]
I'm trying to track down the cause why Scirius only detects when I remove rules from my rule file.

When I first add the source and update, it downloads the complete signature rule file (over HTTP with all rules in a single file).

However when add new rules to the rule file, no change is detected by Scirius.
Removed rules are detected

It works fine if I use the upload option instead.

Is this an issue you recognize?

**Comment by pevma** [comment]
After you add a new rule to the source file - does it appear if you update and push ?

**Comment by Tomasuh** [comment]
Seems like the issue was that the source were not enabled under "Rulesets -> My ruleset -> edit -> Edit categories".
Started to work after that.

Took too long time for me to realize that =)

Anyways thanks for the fast response.
