### ISSUE TITLE
Update all package

### ISSUE THREAD

**Issue by berekese** [StamusNetworks/scirius#128]
Hi, 

A simple question. Actually Suricata use version 4.0.0 however latest version is 4.0.3, do you have something in mind? Are there any way to update to latest packages? 

Thanks!

**Comment by pevma** [comment]
Please ask SELKS related questions via one of the possibilities here -  https://github.com/StamusNetworks/SELKS/wiki/Getting-Help 

If you need to report a bug you are welcome to do it here (for SELKS) - https://github.com/StamusNetworks/SELKS/issues 

If you would like to upgrade SELKS  -  https://github.com/StamusNetworks/SELKS/wiki/SELKS-upgrades

If you need some more info on the doc side please find that here - https://github.com/StamusNetworks/SELKS/wiki  

In principle Suricata running on SELKS is the latest 4.x dev edition.

**Comment by berekese** [comment]
Ops, sorry for not check it first post :) thanks!
