### ISSUE TITLE
404 Error on static files

### ISSUE THREAD

**Issue by acalabrigo** [StamusNetworks/scirius#129]
While trying to run the Django test server, I'm getting a 404 error when Django looks for styles.css and scirius-bundle.js in the static files. These files do not appear to be in the /static directory. Wondering how to resolve this?

**Comment by regit** [comment]
Looks like you are using git master that is currently under heavy work. I need to update the README.rst to include new information.

To do short you need to run webpack in the base directory to get these files generated.

To install:
```
sudo apt-get install npm
sudo npm install -g npm@latest
npm install
sudo npmg install -g webpack
```

Then run webpack:
```
webpack
```

**Comment by acalabrigo** [comment]
Thanks for the response. I didn't realize how in-progress the master is, so I'll go back to the last release instead.
