### ISSUE TITLE
Accidently removed admin rights

### ISSUE THREAD

**Issue by Noname2244** [StamusNetworks/scirius#159]
I was about to add a new user, but instead I change the current user name and made the user none staf/admin.

how do I restore the right from cli/SSH  or add a new admin user ?

**Comment by Noname2244** [comment]
can I git clone scirious to etc/scirious (?) and then run python manage.py createsuperuser?

**Comment by pevma** [comment]
Doubt that will work.

Try - 
```
cd /usr/share/python/scirius/ && \
source bin/activate
python bin/manage.py createuser -h
```
and follow the instructions
