### ISSUE TITLE
Delete generated alerts not works

### ISSUE THREAD

**Issue by esmelnikov** [StamusNetworks/scirius#161]
Hello!

I am using SELKS 5.0 Beta1, Scirius CE v3.0.0.
When you try to delete the "Delete generated alerts" events of any rule from the "Rules activity", the error appears: "Unknown error% s" and the rule events are not deleted.

**Comment by pevma** [comment]
yes i confirm.
We should post a fixed pkg version soon - hopefully early next week.

**Comment by pevma** [comment]
> On 8 Nov 2018, at 20:26, Eduard <notifications@github.com> wrote:
> 
> Hello!
> 
> I am using SELKS 5.0 Beta1, Scirius CE v3.0.0.
> When you try to delete the "Delete generated alerts" events of any rule from the "Rules activity", the error appears: "Unknown error% s" and the rule events are not deleted.
> 

Can you try :
1- 
Set 
KIBANA_VERSION_FULL='6.4.3'
In /etc/scirius/local_settings.py

2- 
Restart Scirius 
supervisorctl restart scirius 

3- 
Try again.

Thank you

**Comment by esmelnikov** [comment]
Added `KIBANA_VERSION_FULL = '6.4.3'` to the file:` /etc/scirius/local_settings.py`
Restarted scirius. The error remained.

**Comment by pevma** [comment]
I can confirm. Seems like a bug.

**Comment by Gatall** [comment]
Is there a solution to this problem?

**Comment by esmelnikov** [comment]
Hello! After installing the updates using the `/opt/selks/Scripts/Setup/selks-upgrade_stamus.sh` script, the removal problem is resolved. Thank!
