### ISSUE TITLE
Scirius unable to start

### ISSUE THREAD

**Issue by lukelee1987** [StamusNetworks/scirius#165]
Hi all, my Scirius and suricata was working previously, but after coming back from my weekend, the terminals were accidentally closed and now I am not able to do so. 

By sending this command : python manage.py runserver, the system prompted me with "ModuleNotFoundError : No module named 'django'. After that I went to check, and Django is already installed with version 1.11.15. 

May I know what could be the root caused and how to I overcome it? Thanks

**Comment by pevma** [comment]
Is that the full output or there is more ?

**Comment by pevma** [comment]
Which Scirius version is that ?

**Comment by lukelee1987** [comment]
I just installed it recently, should be latest one ... Scirius 2.0

**Comment by pevma** [comment]
3.0.1 is the latest currently

**Comment by lukelee1987** [comment]
Tmr I go and double check in office again.

**Comment by lukelee1987** [comment]
Hi yes, its version 3.0.1.

**Comment by lukelee1987** [comment]
This is the full error msg when I execute this command **./manage.py** under scirius folder. 

Traceback (most recent call last):
File "./manage.py", line 8, in <module>
from django.core.management import execute_from_command_line
ModuleNotFoundError : No module named 'django'

**Comment by pevma** [comment]
Could it be full path/folder location issue ? I can not see if it was running before and nothing has changed why would it not run again.

**Comment by lukelee1987** [comment]
Scirius is currently located in the user account: 

/home/username/scirius

**Comment by pevma** [comment]
What is your full command and full output?

**Comment by lukelee1987** [comment]
![image](https://user-images.githubusercontent.com/29053050/49855894-7a134e80-fe29-11e8-8019-017fae3be67a.png)

I am trying to run Scirius service again. Now I cant even view the webpage.

**Comment by lukelee1987** [comment]
I have these listed in /usr/bin, but dont have python (dont have such directory) Is it because they cant detect the python?
![image](https://user-images.githubusercontent.com/29053050/49856874-fb6be080-fe2b-11e8-9e5d-7ce046b16070.png)

**Comment by pevma** [comment]
What happens if you try ``/usr/bin/python manage.py`` in the same folder where you were previously starting scirius ?

**Comment by pevma** [comment]
Can you try  - 
``. bin/activate && python bin/manage.py `` in the same folder? (thanks Nico)

**Comment by lukelee1987** [comment]
There is only one manage.py file which is located in /home/username/scirius/manage.py

**Comment by pevma** [comment]
ok - can you try the command i suggested please?

**Comment by lukelee1987** [comment]
![image](https://user-images.githubusercontent.com/29053050/49859941-b8ae0680-fe33-11e8-9522-c7e6ecb84ad8.png)
Sorry, I missed that. These are the results I got.

**Comment by pevma** [comment]
I meant - cd to the folder where scirius is installed - as you showed here - https://github.com/StamusNetworks/scirius/issues/165#issuecomment-446500545

then execute - ``. bin/activate && python bin/manage.py``

**Comment by lukelee1987** [comment]
![image](https://user-images.githubusercontent.com/29053050/49860678-42aa9f00-fe35-11e8-8c9e-db290f3b37d0.png)
This is the one, am I execute it correctly? my manage.py is under any "bin" folder". Will your command work.

**Comment by pevma** [comment]
what does `ls -lh` show?

**Comment by lukelee1987** [comment]
![image](https://user-images.githubusercontent.com/29053050/49923470-9200d600-feee-11e8-9b13-19d0097f76ba.png)
I think there are some errors ...  is it caused by the nodeJS ?

**Comment by pevma** [comment]
I am not sure what it seems to be the issue but maybe a good idea to start with a clean install.

**Comment by lukelee1987** [comment]
Problem resolved. It was due to the different version of the Python was run. 
It requires Python 2.7 to run, but previously i was running 3.xx. Thanks

**Comment by pevma** [comment]
Thank you for reporting back !

**Comment by lukelee1987** [comment]
![image](https://user-images.githubusercontent.com/29053050/50075201-364d8a00-0219-11e9-9d8f-19584faccdea.png)
I have some issue on the logstash. I am trying to test if logstash can receive the data.

**Comment by pevma** [comment]
Yes - it looks something is not correct with the conf  format.

> -- 
> Regards,
> Peter Manev
