### ISSUE TITLE
Scirius Suricata displaying no data

### ISSUE THREAD

**Issue by lukelee1987** [StamusNetworks/scirius#166]
![sciriussetting_1](https://user-images.githubusercontent.com/29053050/50206796-82c6d000-03a7-11e9-841c-41a971937ad3.PNG)
![suricata_nodata](https://user-images.githubusercontent.com/29053050/50206803-878b8400-03a7-11e9-8635-394f3e83294e.PNG)
Hi all, I have the above settings, but I cant really load the data from Suricata and display. Please advice.

**Comment by lukelee1987** [comment]
I think my logstash's log is combined in Suricata eve.json file, if I am not wrong. What I have in the directory (/var/log/logstash) are logstash.err / logstash.stdout / logstash.log. 

Besides, I check on the logstash.log, and I still sees this Permission denied issue when I already changed the access rights. 
![image](https://user-images.githubusercontent.com/29053050/50210272-a3475800-03b0-11e9-91d5-827bb2a5e2e1.png)

**Comment by pevma** [comment]
It seems you have an explicit `something is wring with your configuration` msg in the logstash log.
If logstash is not working - you would probably have no logs in elasticsearch and naturally Scirius can not display anything. 
First I think you need to fix your logstash config. I am not sure if you have made any changes - but you can use the default one in SELKS 4 - if you run ES 5.x ( https://github.com/StamusNetworks/SELKS/tree/master/staging/etc/logstash/conf.d ) and SELKS 5 if you rune ES 6.x ( https://github.com/StamusNetworks/SELKS/tree/SELKS5/staging/etc/logstash/conf.d )

**Comment by lukelee1987** [comment]
Hi, currently I am using / running ES 6.4. 
I have changed my HOST to my host ip. and also changed the type => "flow"

**Comment by pevma** [comment]
You should probable seek around line 12 (as in the err log message) for some closing statement missing (curly bracket or similar)
Try with the default SELKS 5 config  as well.

**Comment by lukelee1987** [comment]
I have tried to remove the comment line. Now seem some issues has been resolved. Now left these. 
![image](https://user-images.githubusercontent.com/29053050/50272118-b1a97880-0471-11e9-9fdf-419c94c0a254.png)

Is it due to the host I input? The host ip.

**Comment by lukelee1987** [comment]
Is this correct?? pointing to Elasticsearch server:

**Comment by lukelee1987** [comment]
![image](https://user-images.githubusercontent.com/29053050/50272303-490ecb80-0472-11e9-8d73-a29073c2072b.png)

**Comment by pevma** [comment]
@lukelee1987  - did you compare to the default logstahs templates suggested by me multiple times ?

**Comment by pevma** [comment]
Not sure - it seems fine here - https://github.com/StamusNetworks/SELKS/blob/SELKS5/staging/etc/logstash/conf.d/logstash.conf#L80.
I would suggest to conftest the original SELKS5 logstash conf with your set up and see if any different.
You should also have only one conf file in that folder (not multiples).

**Comment by lukelee1987** [comment]
I saw some other discussion on this topic too, explaining that there might be multiple directories for Logstash. Do you know how can I identify them and remove it? Thanks.

**Comment by pevma** [comment]
What discussion are you referring to ?

**Comment by lukelee1987** [comment]
https://stackoverflow.com/questions/39082203/unknown-setting-hosts-for-elasticsearch Looks like they facing the same issue.

**Comment by pevma** [comment]
Looks like they removed the multiple directories (or configs in the same folder) and that solved - based on whats written there.

**Comment by lukelee1987** [comment]
Gosh ..... my apologies, my logstash is version 1. Now seems ok. Is this correct? 

![image](https://user-images.githubusercontent.com/29053050/50275731-04d3f900-047b-11e9-8245-cc8525f29eb6.png)

**Comment by lukelee1987** [comment]
since I am using the oldest version 1.5.3. Do you think I should upgrade it to the latest one? Is there a shortcut of doing it?

**Comment by pevma** [comment]
Yes please - 1.x is not supported neither from Logstahs nor from us.
I would suggests to recheck your whole set up as well.
Thanks for reporting back.

**Comment by lukelee1987** [comment]
Hi, may I know is there any guide to upgrade it without any error?

**Comment by lukelee1987** [comment]
I have upgraded the Logstash version. But there is still no data coming in to Suricata.

**Comment by pevma** [comment]
Is this a SELKS installation ?

**Comment by lukelee1987** [comment]
Kind of. But I installed it separately. Scirius, Elasticsearch, Logstash, Kibana and Suricata. 
Now my Kibana's Visualize not showing Data. 

![image](https://user-images.githubusercontent.com/29053050/50474059-6d325580-09fa-11e9-87e3-a2c26e736d30.png)

**Comment by pevma** [comment]
Then  it is probably best if you follow up the instructions by Elasticsearch docs of how to do that for the kind of OS you are using. (example - https://www.elastic.co/guide/en/elastic-stack/current/installing-elastic-stack.html)

Until the installations is done and the components configured (SELKS does that done by default) properly  there most likely would be no data available in the dashboards / Kiabna and Scirius respectively.

**Comment by lukelee1987** [comment]
Is there a way I can test if these platforms are able to communicate to each other, like reading data. I cant ensure there are data and how they are being transferred. Thanks.

**Comment by pevma** [comment]
yes - follow the documentation , use the same configs as in SELKS and check for any errors in the respective logs. Once that is in place with no errors  - you should be seeing data i think.

**Comment by lukelee1987** [comment]
Pevma, the challenge is that I installed SELKS separately. And there are too many configurations need to be taken care of.
