### ISSUE TITLE
Remove rule suppression

### ISSUE THREAD

**Issue by problematiq** [StamusNetworks/scirius#167]
I'm not sure if i'm blind or what, but i cannot for the life of me see a way to remove a rule suppression. Is this a feature that exists?

**Comment by regit** [comment]
One way to do it it go on information tab for the rule:

![screenshot from 2018-12-20 17-11-58](https://user-images.githubusercontent.com/308616/50296295-7cedef00-047a-11e9-8c5d-9881b7fe4a8c.png)

And then click on the ID of the suppression (here 71).

Then you can click delete in the left menu of the next page:

![screenshot from 2018-12-20 17-12-10](https://user-images.githubusercontent.com/308616/50296318-91ca8280-047a-11e9-853e-f334b6c144c5.png)

**Comment by problematiq** [comment]
Thank you very much!
