### ISSUE TITLE
problem with -javaagent on SELKS

### ISSUE THREAD

**Issue by sarahmech** [StamusNetworks/scirius#168]
![image](https://user-images.githubusercontent.com/46159317/50443263-c028e180-0902-11e9-8e29-166667519316.png)
Hello, I have installed the latest version of SELKS, and when I install apm server it appears "You have correctly setup APM Server" and when I start kibana, it says "There's no APM index pattern available. To use the Query bar, please choose to import The APM index pattern in the Setup Instructions "can you help me please?

**Comment by pevma** [comment]
Do you have working dashboards ? (If you click on `Dashboards` and then choose any)

**Comment by sarahmech** [comment]
![image](https://user-images.githubusercontent.com/46159317/50443895-b6ed4400-0905-11e9-90be-77e6c0224a3d.png)
![image](https://user-images.githubusercontent.com/46159317/50443922-cbc9d780-0905-11e9-8eaf-1c1bf5573e6b.png)

**Comment by pevma** [comment]
Did you run the first time set up scripts/procedure?

**Comment by pevma** [comment]
As described here - https://github.com/StamusNetworks/SELKS/wiki/SELKS-5.0-RC1 in the docs ?

**Comment by sarahmech** [comment]
Yes, I have done all this

**Comment by pevma** [comment]
ok good - so  if everything was completed successfully  - you can go ahead and click on the`setup instructions` button and follow the instructions to set it up. It is not something that is autosetup by SELKS - it is up to you to enable/setup if you would like.

**Comment by sarahmech** [comment]
![image](https://user-images.githubusercontent.com/46159317/50446864-90380900-0917-11e9-8772-b4f03f131169.png)

Launch APM -->

![image](https://user-images.githubusercontent.com/46159317/50446907-cffef080-0917-11e9-94ae-e6e113741739.png)

this is displayed!!

**Comment by sarahmech** [comment]
![image](https://user-images.githubusercontent.com/46159317/50446994-72b76f00-0918-11e9-8963-c5635b3d8178.png)

**Comment by pevma** [comment]
This might help too - https://www.elastic.co/guide/en/apm/get-started/current/install-and-run.html .
You can also probably refer to the Elastic help forums/faq for set up.

**Comment by sarahmech** [comment]
![image](https://user-images.githubusercontent.com/46159317/50447016-a5616780-0918-11e9-85e6-6d31e5a282b5.png)
now, I don't know how to add javaagent

**Comment by pevma** [comment]
Closing since it does not seem to be a problem with SELKS.
