### ISSUE TITLE
some URIs below /rule/ are doubled when served trough fastcgi

### ISSUE THREAD

**Issue by tmarchst** [StamusNetworks/scirius#18]
When accessing URLs like https://scirius.site.inet/rules/ruleset/3/ the request goes to https://scirius.site.inet/rules/ruleset/rules/ruleset/3/
or
https://scirius.tah.insite/rules/source/add/rules/source/3/rules/source/add/rules/source/3/
/accouts/login seems to be affected to

However running Scirius via the integrated webserver it runs fine.

**Comment by pevma** [comment]
What is the result if you use:
https://scirius.site.inet/rules/

instead of the way you mentioned:
https://scirius.site.inet/rules/ruleset/3/ 
?

**Comment by tmarchst** [comment]
https://scirius.site.inet/rules/ works fine, even the links that leads to https://scirius.site.inet/rules/
but the link that should point to 
https://scirius.site.inet/rules/ruleset/3/ leads to https://scirius.site.inet/rules/ruleset/rules/ruleset/3/
When click on that link i got a 404. Seen on Debug Output below.

When enter the Credentials at the Login Page nothing seems to happen. But Tokens are received and sent back. when deleting /accounts/login from the Addressbar i'm logged in.  

```

Page not found (404)
Request Method: 	GET
Request URL: 	https://scirius.tah.insite/rules/ruleset/rules/ruleset/3/rules/ruleset/rules/ruleset/3/

Using the URLconf defined in scirius.urls, Django tried these URL patterns, in this order:

    ^admin/
    ^rules/ ^$ [name='index']
    ^rules/ ^about/$ [name='about']
    ^rules/ ^search$ [name='search']
    ^rules/ ^es$ [name='elasticsearch']
    ^rules/ ^source/$ [name='sources']
    ^rules/ ^source/add$ [name='add_source']
    ^rules/ ^source/(?P<source_id>\d+)/$ [name='source']
    ^rules/ ^source/(?P<source_id>\d+)/update$ [name='update_source']
    ^rules/ ^source/(?P<source_id>\d+)/diff$ [name='diff_source']
    ^rules/ ^source/(?P<source_id>\d+)/changelog [name='changelog_source']
    ^rules/ ^source/(?P<source_id>\d+)/edit$ [name='edit_source']
    ^rules/ ^source/(?P<source_id>\d+)/delete$ [name='delete_source']
    ^rules/ ^sourceupdate/(?P<update_id>\d+)$ [name='sourceupdate']
    ^rules/ ^category/$ [name='categories']
    ^rules/ ^category/(?P<cat_id>\d+)/$ [name='category']
    ^rules/ ^category/(?P<cat_id>\d+)/suppress$ [name='suppress_category']
    ^rules/ ^ruleset/$ [name='rulesets']
    ^rules/ ^ruleset/add$ [name='rulesets']
    ^rules/ ^ruleset/(?P<ruleset_id>\d+)/$ [name='ruleset']
    ^rules/ ^ruleset/(?P<ruleset_id>\d+)/update$ [name='update_ruleset']
    ^rules/ ^ruleset/(?P<ruleset_id>\d+)/edit$ [name='edit_ruleset']
    ^rules/ ^ruleset/(?P<ruleset_id>\d+)/delete$ [name='delete_ruleset']
    ^rules/ ^ruleset/(?P<ruleset_id>\d+)/addsupprule$ [name='addsupprule']
    ^rules/ ^ruleset/(?P<ruleset_id>\d+)/display$ [name='display_ruleset']
    ^rules/ ^ruleset/(?P<ruleset_id>\d+)/export$ [name='export_ruleset']
    ^rules/ ^ruleset/(?P<ruleset_id>\d+)/copy$ [name='copy_ruleset']
    ^rules/ ^ruleset/(?P<ruleset_id>\d+)/changelog [name='changelog_ruleset']
    ^rules/ ^rule/(?P<rule_id>\d+)/suppress$ [name='suppress_rule']
    ^rules/ ^rule/pk/(?P<rule_id>\d+)/$ [name='rule']
    ^rules/ ^rule/(?P<rule_id>\d+)/$ [name='rule_sid']
    ^accounts/
    ^suricata/
    ^$
    ^kibana/(?P<path>.*)$
    ^elasticsearch/(?P<path>.*)$

The current URL, rules/ruleset/rules/ruleset/3/, didn't match any of these.

```

**Comment by pevma** [comment]
I am not understanding - why do you explicitly need to go to:
https://scirius.site.inet/rules/ruleset/3/

**Comment by tmarchst** [comment]
Because the link and the Ruleset site to a specific Ruleset is generated as https://scirius.site.inet/rules/ruleset/rules/ruleset/3/ while it should be https://scirius.site.inet/rules/ruleset/3/
When clicking the link that was generated the debug message states that i tryed to visit
https://scirius.site.inet/rules/ruleset/rules/ruleset/3/rules/ruleset/rules/ruleset/3/

**Comment by regit** [comment]
Hi,

If you are using nginx to serve the fcgi, you need to tune  ```/etc/nginx/fastcgi_params``` by removing the following line which is django incompatible:
```
fastcgi_param SCRIPT_NAME
```
Let us know if it helps.

**Comment by tmarchst** [comment]
Thanks for the hint.
Scirius working fine now.
