### ISSUE TITLE
Scirius "No Data Available"

### ISSUE THREAD

**Issue by josass** [StamusNetworks/scirius#188]
Have been attempting to install Scirius following this "https://scirius.readthedocs.io/en/latest/installation-ce.html" install guide. I am installing this on an Ubuntu 18.04 LXD container running Suricata 4.1.4, ElasticSearch 6.8.2, Kibana 6.8.2 and Logstash 6.8.1. With the exception of Scirius, every other service works fine. Unfortunately, it seems that Scirius is displaying the message "No Data Available" even though both my other services are working and receiving data. Likely related to this issue, is that in the terminal there are errors indicating that Scirius cannot find rules with certain sids(this happens every time the administration page is accessed via url). I have posted some screenshots of what I am seeing along with some options from my settings.py file. 
![SciriusHome](https://user-images.githubusercontent.com/53945169/63265642-195fcf80-c25c-11e9-92e1-dc667f9f45fd.png)
![sciriusnodata](https://user-images.githubusercontent.com/53945169/63265660-22e93780-c25c-11e9-95b0-517f5a710a29.png)
![scirius-missing](https://user-images.githubusercontent.com/53945169/63265673-267cbe80-c25c-11e9-9503-71c40355269f.png)
![elasticonf](https://user-images.githubusercontent.com/53945169/63265681-2c729f80-c25c-11e9-8c6a-6198b05d3313.png)

**Comment by pevma** [comment]
Do the “host” and “localhost” résolve properly ?

Are there any errors in the scirius logs ?

> -- 
> Regards,
> Peter Manev

**Comment by josass** [comment]
@pevma, "host" and "localhost" seem to be resolving correctly. After some testing, I found that if they weren't resolving than hunt would show 0 alerts and the Scirius Administration page would display elastisearch as grey and indicate "no data for period".

As for the scirius logs I have checked the /var/log/scirius/elasticsearch.log and see the following:
![elasticnodata](https://user-images.githubusercontent.com/53945169/63272122-7b730180-c269-11e9-970e-6ba711cc40b6.png)
![healtnodata](https://user-images.githubusercontent.com/53945169/63272128-7f9f1f00-c269-11e9-8dcb-3352422ca685.png)
There are a few instances like this that display "No data", as for any other logs I am not sure where the rest of the Scirius log files are held.

**Comment by josass** [comment]
After consulting issue #89 , I found that my error was caused by not using the hostname of my device in scirius > suricata > edit. As shown below:
![sciriusworking](https://user-images.githubusercontent.com/53945169/63343628-7327ce80-c31c-11e9-8645-887dcca6becb.png)
With that done, everything now seems to show up properly.
