### ISSUE TITLE
Auto update of ruleset

### ISSUE THREAD

**Issue by AtzeDeVries** [StamusNetworks/scirius#20]
It would be nice to have some way of auto updating the rules
it shoud
* Download new rules
* Deploy them to suricata

**Comment by regit** [comment]
Hello @AtzeDeVries 

You can already do that by using manage.py:
```
python manage.py updatesuricata
```

It is for example used in SELKS: https://github.com/StamusNetworks/SELKS/blob/b830c2fac0d283acc2a915b2a76f44b47a82aecc/staging/config/hooks/chroot-inside-Debian-Live.chroot#L113
