### ISSUE TITLE
Unable to change rule action to Drop

### ISSUE THREAD

**Issue by ssvinarev** [StamusNetworks/scirius#212]
Hi!

Unable to change rule action from "alert" to "drop" in Scirius:
1. Find a rule by its signature_id, go to that rule.
2. Action -> Edit rule -> Change "Action" to Drop -> Apply transformation to ruleset, containing that rule -> Valid
Fine, now I can see, that there is a rule transformation in a ruleset (action is "drop" now). But dropping traffic doesn't work. Like earlier, it just alerts when rule hits.

The only working way I found to really change action is to find the rule in /etc/suricata/rules/scirius.rules and edit action from alert to drop. And reload the rules (suricatasc -c reload-rules).
This works - traffic is dropped now.

But this is, of course, the wrong way of editing rules.
What is a correct and working procedure of editing rules in Scirius?
And how to log dropped events?

Thanks!

P.S.:
Its af_packet in ips mode, inline.
- drop:
      enabled: yes
      filename: drop.log
      append: yes

**Comment by pevma** [comment]
Did you try to push and update the ruelset - from the suricata menu in Scirius ?

**Comment by ssvinarev** [comment]
No.. That fixed the problem. Thanks!

One more thing: how to log dropped events? Need to log all dropped hits.
Adding
_- drop:
      enabled: yes
      filename: drop.log
      append: yes_
to
_outputs:_
and to
_logging:
outputs:_
of _/etc/suricata/suricata.yaml_ and _/etc/suricata/selks6-addin.yaml_ doesn't help.

**Comment by pevma** [comment]
Use the eve-log section (example)
https://github.com/OISF/suricata/blob/master/suricata.yaml.in#L246

**Comment by ssvinarev** [comment]
Tried already- it doesn't work. The log is empty, while traffic is being blocked.

**Comment by pevma** [comment]
Did you make the change in ``selks6-addin.yaml`` ?

**Comment by ssvinarev** [comment]
Yes. Tried in selks6-addin.yaml, in suricata.yaml, both.

# suricata --dump-config | grep drop
outputs.1.eve-log.types.7 = drop
outputs.1.eve-log.types.7.drop = (null)
outputs.1.eve-log.types.7.drop.alerts = yes
outputs.1.eve-log.types.7.drop.flows = all
outputs.12 = drop
outputs.12.drop = (null)
outputs.12.drop.enabled = yes
outputs.12.drop.filename = drop.log
outputs.12.drop.append = yes
logging.outputs.3 = drop
logging.outputs.3.drop = (null)
logging.outputs.3.drop.enabled = yes
logging.outputs.3.drop.filename = /var/log/suricata/drop.log
logging.outputs.3.drop.append = yes

**Comment by pevma** [comment]
Actually, can you disable the drop/log and use only eve.json? those events should be there.

**Comment by ssvinarev** [comment]
Yes. Actually, this is how it is being done now.
I think, issue can be closed.

**Comment by pevma** [comment]
ok thank you !
