### ISSUE TITLE
Unable to run the script manage.py

### ISSUE THREAD

**Issue by XXXereXXX** [StamusNetworks/scirius#213]
Hello there,

I tried to install Scirius on Ubuntu 18.04, everything was going well but I encountered this error message when I ran "python manage.py migrate". 

_"SyntaxError: Non-ASCII character '\xe2' in file /usr/local/lib/python2.7/dist-packages/django_tables2/tables.py on line 129, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details."_

After that, I put the line "# -*- coding: utf8 -*-" at the top of the file "/usr/local/lib/python2.7/dist-packages/django_tables2/tables.py". Then, I came across new error as follows.

_File "/usr/local/lib/python2.7/dist-packages/django_tables2/tables.py", line 188
   class Table(metaclass=DeclarativeColumnsMetaclass):
                                      ^
SyntaxError: invalid syntax_

![Screenshot from 2020-12-13 11-43-08](https://user-images.githubusercontent.com/73839920/102006743-b2133c00-3d38-11eb-9ca3-54167f9463e0.png)

Could you help me to solve the issue, please?

**Comment by JSkier21** [comment]
I ran into this too initially.

Make sure you run python3 instead of python for the initialization and follow commands to get the server up. I would revert the change you made first as well.

**Comment by XXXereXXX** [comment]
Yes I should have used python3.

Thanks for your comment.
