### ISSUE TITLE
Changelog include disabled rules

### ISSUE THREAD

**Issue by xrl** [StamusNetworks/scirius#22]
Can the system report when rules were disabled through the web interface? This would help to make a more complete changelog.

**Comment by regit** [comment]
Sorry for the lag. Do you mean displaying differently in the changelog of a ruleset the disabled rules ?

**Comment by xrl** [comment]
Yes, we'd like to track when the rules were toggled and by whom.

**Comment by regit** [comment]
Interesting. I will try to cook that.
