### ISSUE TITLE
Hyperlink to EveBox contains wrong character

### ISSUE THREAD

**Issue by ipworkx** [StamusNetworks/scirius#220]

**Comment by ipworkx** [comment]
The hyperlink in scirius to hunt in Evebox contains the wrong character.
It is the following:
https://u006.system.ipworkx.loc/evebox/#/events;q=dest_ip:"192.168.11.137"

Officially it should be:
https://u006.system.ipworkx.loc/evebox/#/events?q=dest_ip:"192.168.11.137"

The question mark is missing and should be there other while it will not query Evebox at all and just shows all the records in stead of only a query for the IP address.

<img width="1410" alt="Screenshot 2021-01-14 at 08 27 00" src="https://user-images.githubusercontent.com/12648411/104558697-7d4e1980-5643-11eb-8ed9-7d115acc6085.png">

**Comment by pevma** [comment]
This is fixed.
