### ISSUE TITLE
Error add public source

### ISSUE THREAD

**Issue by ngoc2807** [StamusNetworks/scirius#234]
![ảnh](https://user-images.githubusercontent.com/51168970/120935949-65c91780-c72f-11eb-900c-5f4c7c4bde1d.png)
I got that error when I added public source.
Something wrong? 
Help me plz. Tks

**Comment by pevma** [comment]
Hi!

Is simple wget working from the command line where Scirius is installed ?

> -- 
> Regards,
> Peter Manev

**Comment by ngoc2807** [comment]
> 
> Hi! Is simple wget working from the command line where Scirius is installed ?
> […](#)
> -- Regards, Peter Manev On 6 Jun 2021, at 20:28, ngoc2807 ***@***.***> wrote: ﻿ I got that error when I added public source. Something wrong? Help me plz. Tks — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

![ảnh](https://user-images.githubusercontent.com/51168970/120936901-9e1f2480-c734-11eb-8327-e70eac6b9fb2.png)
you mean like this

**Comment by pevma** [comment]
No, sorry  I meant - if you wget download the ruleset.

**Comment by Faiz2035** [comment]
` python3 manage.py createcachetable` cachetable needs to be created manually

**Comment by zentavr** [comment]
> ` python3 manage.py createcachetable` cachetable needs to be created manually

In which folder should I invoke this command?

**Comment by Faiz2035** [comment]
> > `python3 manage.py createcachetable` cachetable needs to be created manually
> 
> In which folder should I invoke this command?

The root directory of scirius is fine

**Comment by pevma** [comment]
This should have been be fixed in subsequent releases of your version , please feel free to reopen if needed.
