### ISSUE TITLE
Running Scirius on OS X:  "Unable to get data from Elasticsearch" and Suricata is red

### ISSUE THREAD

**Issue by Drewshg312** [StamusNetworks/scirius#26]
Hi! I'm running Scirius on os x 10.10.4. Suricata, Elasticsearch, Logstash and Kibana installed from Homebrew. Suricata is working fine but in Scirius in 'System Status' everything is green except of Suricata(it's red). What does that mean and how can I address this? 

Also It shows correct Elasticsearch version and cluster name detected as well as status green (which I guess supposed to be a good sign)... But it always shows `"Unable to get data from Elasticsearch"` message on red background...

And under kibana dashboards says: `Failed to get data`

Please help. Thank you!

**Comment by regit** [comment]
Hi,

Regarding suricata status, you need to enable unix-command in your suricata YAML.

For elasticsearch, check that elasticsearch index related variable are correct (see https://github.com/StamusNetworks/scirius/blob/master/scirius/settings.py#L113).

**Comment by Drewshg312** [comment]
Thank you for reply!

1 - Enabled `unix-command` in **suricata.yaml**:

    unix-command:
      enabled: yes
      filename: custom.socket

Restarted suricata and scirius - still red (((

2 - my indexes i elasticsearch look like this:
`logstash-2015.05.24; logstash-2015.06.04; logstash-2015.06.05; logstash-2015.06.06;...`
So in **local_settings.py** I've changed default `"logstash-"` to  `"logstash-*"` and restarted scirius - still have `"Unable to get data from Elasticsearch"` on red background

3 - in **local_settings.py** Ive also have:

    USE_KIBANA = True
    # Use django as a reverse proxy for kibana request
    # This will allow you to use scirius authentication to control
    # access to Kibana
    KIBANA_PROXY = False
    # Kibana URL
    KIBANA_URL = "http://localhost:5601"

But still have under kibana dashboards says: `Failed to get data`

Please, what am I missing?

**Comment by Drewshg312** [comment]
Well I think I know what's with my suricata - there is a bug suricata with BSD-flavored operation systems... Getting `Unable to change permission on socket: Invalid argument (22)` -- https://redmine.openinfosecfoundation.org/issues/1353

But I still don't understand what's with my elasticsearch and kibana
![untitled](https://cloud.githubusercontent.com/assets/10493450/8513357/afb35c42-231c-11e5-9222-d5510543921d.jpg)

**Comment by Drewshg312** [comment]
![untitled1](https://cloud.githubusercontent.com/assets/10493450/8513606/55bcde9c-2327-11e5-9eee-eee03c4edd48.jpg)

**Comment by regit** [comment]
Could you have one specific index for kibana in elasticsearch ?

**Comment by Drewshg312** [comment]
Is that what you mean?
![untitled3](https://cloud.githubusercontent.com/assets/10493450/8513645/847b45ec-2328-11e5-81c4-bbe5c62fce38.jpg)

**Comment by regit** [comment]
Yes, that's it! kibana-int is hard coded and you are using .kibana. I'll try to cook a patch to fix this.

**Comment by Drewshg312** [comment]
Can't I just try deleting it?

**Comment by regit** [comment]
No, I've just pushed patches on master. Can you try them ?

In your local_settings.py, set
```
KIBANA_VERSION=4
KIBANA_INDEX=".kibana"
```

**Comment by Drewshg312** [comment]
doesn't work(((
I've removed previos scirius and cloned again:

    git clone https://github.com/StamusNetworks/scirius /usr/local/var/www/scirius

made all changes like you've written and started server:
    
    python /usr/local/var/www/scirius/manage.py runserver

and got this:
    You have unapplied migrations; your app may not work properly until they are applied.
    Run 'python manage.py migrate' to apply them.

and in browser got this:
![untitled](https://cloud.githubusercontent.com/assets/10493450/8518198/b7dd9a4e-237c-11e5-9e14-54381a5afe09.jpg)

**Comment by regit** [comment]
Try to run the migrate command as proposed.

**Comment by Drewshg312** [comment]
oh yeah! Stupid me! I was already sleeping! I've run the migrate command and now everything works fine!!! Waiting suricata 2.1beta5 - they promise to fix unix-socket on BSD operating systems... Thank you very much! If I notice something I'll let you know!

**Comment by Drewshg312** [comment]
Well when I recreated all my rulesets I've switched to **suricata** tab, entered the correct name, description and output directory like this (without backslash at the end): `/usr/local/suricata/rules`
without selecting any ruleset and pressed enter and got this:
![untitled](https://cloud.githubusercontent.com/assets/10493450/8529343/25e6a08e-23ce-11e5-835b-0cbebacb2394.jpg)
I've tried to log out and login again many times and every time I'm getting the same((( How to fix it?

**Comment by Drewshg312** [comment]
So I've tried to remove scirius completely again and do everything from scratch - and now I have the same issue that it was before: `"Unable to get data from Elasticsearch"` message on red background...
And under kibana dashboards says: `Failed to get data` (((( It worked before! what's the problem???

**Comment by Drewshg312** [comment]
I've got this red "Unable to get data from Elasticsearch" message again…

**Comment by Drewshg312** [comment]
well I've found out what's happening… Will open new issue…
