### ISSUE TITLE
Unable to update Snort Community Rules

### ISSUE THREAD

**Issue by benvon** [StamusNetworks/scirius#27]
I am attempting to add the Snort Community Rules as one of my ruleset sources, but I am unable to load them due to this error:

> SuspiciousOperation at /rules/source/10/update
> Suspect tar file contains a invalid name 'community-rules'
> Request Method:	GET
> Request URL:	http://*********:8000/rules/source/10/update
> Django Version:	1.8
> Exception Type:	SuspiciousOperation
> Exception Value:	
> Suspect tar file contains a invalid name 'community-rules'
> Exception Location:	/var/www/scirius/rules/models.py in handle_rules_in_tar, line 203
> Python Executable:	/usr/bin/python
> Python Version:	2.7.6
> Python Path:	
> ['/usr/local/lib/python2.7/dist-packages/git/ext/gitdb',
>  '/var/www/scirius',
>  '/usr/local/lib/python2.7/dist-packages/pip-7.0.3-py2.7.egg',
>  '/usr/lib/python2.7',
>  '/usr/lib/python2.7/plat-x86_64-linux-gnu',
>  '/usr/lib/python2.7/lib-tk',
>  '/usr/lib/python2.7/lib-old',
>  '/usr/lib/python2.7/lib-dynload',
>  '/usr/local/lib/python2.7/dist-packages',
>  '/usr/lib/python2.7/dist-packages',
>  '/usr/local/lib/python2.7/dist-packages/gitdb/ext/smmap']

I would really like to use the Snort rules in addition to of the ET rules (which work fine, btw).

**Comment by regit** [comment]
It seems they don't respect the "de-facto stanard" of putting the rules files under the rules directory. Instead the 'community-rules' directory is used. That completely screw up the current parsing.

**Comment by benvon** [comment]
Yes, agreed 100%. 

However, given that the Snort community ruleset is a significant source of rules, it would be very nice to support this convention.

**Comment by regit** [comment]
I've updated the code and current git seems to handle snort community rules "fine". Only issue is that everything is in one single category.
