### ISSUE TITLE
Warnings when starting server (On OS X)

### ISSUE THREAD

**Issue by Drewshg312** [StamusNetworks/scirius#28]
Hi again! 
First - I really love this scirius project and want it to work as smooth as possible... Thank you for it!

Second:
When I start server on os x 10.10.4 yosemite getting this warnings in the shell:

    $ python /usr/local/var/www/scirius/manage.py runserver
    /usr/local/lib/python2.7/site-packages/django_tables2/tables.py:175: RemovedInDjango19Warning: SortedDict is deprecated and will be removed in Django 1.9.
      attrs["base_columns"] = SortedDict(parent_columns)
    
    /usr/local/lib/python2.7/site-packages/django_tables2/tables.py:197: RemovedInDjango19Warning: SortedDict is deprecated and will be removed in Django 1.9.
      attrs["base_columns"].update(SortedDict(cols))
    
    /usr/local/lib/python2.7/site-packages/django_tables2/tables.py:175: RemovedInDjango19Warning: SortedDict is deprecated and will be removed in Django 1.9.
      attrs["base_columns"] = SortedDict(parent_columns)
    
    /usr/local/lib/python2.7/site-packages/django_tables2/tables.py:197: RemovedInDjango19Warning: SortedDict is deprecated and will be removed in Django 1.9.
      attrs["base_columns"].update(SortedDict(cols))
    
    Performing system checks...
    
    System check identified some issues:
    
    WARNINGS:
    rules.Category.created_date: (fields.W161) Fixed default value provided.
    	HINT: It seems you set a fixed date / time / datetime value as default for this field. This may not be what you want. If you want to have the current date as default, use `django.utils.timezone.now`
    rules.SourceAtVersion.updated_date: (fields.W161) Fixed default value provided.
    	HINT: It seems you set a fixed date / time / datetime value as default for this field. This may not be what you want. If you want to have the current date as default, use `django.utils.timezone.now`
    rules.SourceUpdate.created_date: (fields.W161) Fixed default value provided.
    	HINT: It seems you set a fixed date / time / datetime value as default for this field. This may not be what you want. If you want to have the current date as default, use `django.utils.timezone.now`
    
    System check identified 3 issues (0 silenced).
    July 07, 2015 - 02:50:30
    Django version 1.8.2, using settings 'scirius.settings'
    Starting development server at http://127.0.0.1:8000/
    Quit the server with CONTROL-C.

How to address these issues? Any ideas why am I getting them? Thank you!

**Comment by regit** [comment]
Regarding warning on SortedDict this is on djano_tables2 so you may need to warn them directly.

**Comment by regit** [comment]
The other warning should be fixed by 1f75865

**Comment by regit** [comment]
Closing as only django_tables2 warning is remaining.

**Comment by Drewshg312** [comment]
I've recloned the master branch and got the same warnings

**Comment by regit** [comment]
Do you confirm you are seing:
```
rules.Category.created_date: (fields.W161) Fixed default value provided.
    HINT: It seems you set a fixed date / time / datetime value as default for this field. This may not be what you want. If you want to have the current date as default, use `django.utils.timezone.now`
```

**Comment by regit** [comment]
OK, I'm seeing this with Django 1.8.3 too.

**Comment by regit** [comment]
For django_tables2 warning, it is fixed after running:
```
pip install --upgrade django-tables2
```

**Comment by Drewshg312** [comment]
Getting this:

    WARNINGS:
    rules.Category.created_date: (fields.W161) Fixed default value provided.
    	HINT: It seems you set a fixed date / time / datetime value as default for this field. This may not be what you want. If you want to have the current date as default, use `django.utils.timezone.now`
    rules.SourceAtVersion.updated_date: (fields.W161) Fixed default value provided.
    	HINT: It seems you set a fixed date / time / datetime value as default for this field. This may not be what you want. If you want to have the current date as default, use `django.utils.timezone.now`
    rules.SourceUpdate.created_date: (fields.W161) Fixed default value provided.
    	HINT: It seems you set a fixed date / time / datetime value as default for this field. This may not be what you want. If you want to have the current date as default, use `django.utils.timezone.now`

**Comment by Drewshg312** [comment]
I ran `git pull` hoping to get rid of warnings and now getting this:
![1](https://cloud.githubusercontent.com/assets/10493450/9389266/fbb4a972-471e-11e5-876a-2db1df18eb5a.jpg)
Shell output:

    $ /usr/local/bin/python /usr/local/var/www/scirius/manage.py runse
    /usr/local/lib/python2.7/site-packages/django_tables2/tables.py:175: RemovedInDjango19Warning: SortedDict is deprecated and will be removed in Django 1.9.
      attrs["base_columns"] = SortedDict(parent_columns)
    
    /usr/local/lib/python2.7/site-packages/django_tables2/tables.py:197: RemovedInDjango19Warning: SortedDict is deprecated and will be removed in Django 1.9.
      attrs["base_columns"].update(SortedDict(cols))
    
    /usr/local/lib/python2.7/site-packages/django_tables2/tables.py:175: RemovedInDjango19Warning: SortedDict is deprecated and will be removed in Django 1.9.
      attrs["base_columns"] = SortedDict(parent_columns)
    
    /usr/local/lib/python2.7/site-packages/django_tables2/tables.py:197: RemovedInDjango19Warning: SortedDict is deprecated and will be removed in Django 1.9.
      attrs["base_columns"].update(SortedDict(cols))
    
    Performing system checks...
    
    System check identified no issues (0 silenced).
    August 20, 2015 - 16:30:44
    Django version 1.8, using settings 'scirius.settings'
    Starting development server at http://127.0.0.1:8000/
    Quit the server with CONTROL-C.
    /usr/local/lib/python2.7/site-packages/django_tables2/tables.py:178: RemovedInDjango19Warning: SortedDict is deprecated and will be removed in Django 1.9.
      extra = SortedDict()

**Comment by regit** [comment]
Hello @Drewshg312 I have just pushed the migration. See https://docs.djangoproject.com/en/1.8/topics/migrations/ for information on Django migration. You should now be able to fix your installation by running
```
git pull
python manage.py migrate
```

Regarding the warning, as stated before this is not a scirius bug, please update django-tables2. For instance by running:
```
pip install --upgrade django-tables2
```

**Comment by Drewshg312** [comment]
Thanx! Works now!
