### ISSUE TITLE
Error when creating 'suricata' instance with no ruleset selected

### ISSUE THREAD

**Issue by Drewshg312** [StamusNetworks/scirius#29]
When I recreated all my rulesets I've switched to **suricata** tab, entered the correct name, description and output directory like this (without backslash at the end): `/usr/local/suricata/rules`
**without selecting any ruleset** and pressed enter and got this:
![untitled](https://cloud.githubusercontent.com/assets/10493450/8529343/25e6a08e-23ce-11e5-835b-0cbebacb2394.jpg)
I've tried to log out and login again many times and every time I'm getting the same(((

Seems like a bug...

The only thing that helped is reinstallation

**Comment by regit** [comment]
It should be fixed in current code.
