### ISSUE TITLE
(OS X) Error when trying to start server with reverse proxy for kibana

### ISSUE THREAD

**Issue by Drewshg312** [StamusNetworks/scirius#30]
When using `KIBANA_PROXY = True` in **local_settings.py** getting:

    $ python /usr/local/var/www/scirius/manage.py runserver
    /usr/local/lib/python2.7/site-packages/django_tables2/tables.py:175: RemovedInDjango19Warning: SortedDict is deprecated and will be removed in Django 1.9.
      attrs["base_columns"] = SortedDict(parent_columns)
    
    /usr/local/lib/python2.7/site-packages/django_tables2/tables.py:197: RemovedInDjango19Warning: SortedDict is deprecated and will be removed in Django 1.9.
      attrs["base_columns"].update(SortedDict(cols))
    
    Traceback (most recent call last):
      File "/usr/local/var/www/scirius/manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
      File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
        utility.execute()
      File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
        django.setup()
      File "/usr/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
        apps.populate(settings.INSTALLED_APPS)
      File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 89, in populate
        "duplicates: %s" % app_config.label)
    django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: revproxy

Any ideas how to solve?

**Comment by regit** [comment]
It looks like 'revproxy' is already loaded when django try to install the apps. Try to comment the two last lines of scirius/settings.py to check that.

By the way, I don't see how it is possible without edit of settings.py.

**Comment by Drewshg312** [comment]
That works!!! Thanx!

**Comment by regit** [comment]
Hello @Drewshg312 , did you edit the settings.py before that ?

**Comment by Drewshg312** [comment]
I've edited the local_settings.py

**Comment by regit** [comment]
Yes, what did you put in here ? Did you just set some variables ?

**Comment by Drewshg312** [comment]
No my local_settings.py is just a duplicate of settings.py with this changes:

    # Elastic search
    USE_ELASTICSEARCH = True
    #ELASTICSEARCH_ADDRESS = "127.0.0.1:9200"
    ELASTICSEARCH_ADDRESS = "localhost:9200"
    # You can use a star to avoid timestamping expansion for example 'logstash-*'
    ELASTICSEARCH_LOGSTASH_INDEX = "logstash-*"
    # use hourly, daily to indicate the logstash index building recurrence
    ELASTICSEARCH_LOGSTASH_TIMESTAMPING = "daily"
    
    # Kibana
    USE_KIBANA = True
    KIBANA_VERSION = 4
    KIBANA_INDEX = ".kibana"
    # Use django as a reverse proxy for kibana request
    # This will allow you to use scirius authentication to control
    # access to Kibana
    KIBANA_PROXY = True
    # Kibana URL
    KIBANA_URL = "https://server.kibana"
    # Number of dashboards to display
    KIBANA_DASHBOARDS_COUNT = 20

and commented two last lines:

    #if KIBANA_PROXY:
    #    INSTALLED_APPS += ('revproxy',)

**Comment by regit** [comment]
OK, now I got it. You are not supposed  to have the if KIBANA_PROXY at the end of your local_settings.py. In fact you should just copy the value you are modifying from default one.
