### ISSUE TITLE
osx homebrew package

### ISSUE THREAD

**Issue by Drewshg312** [StamusNetworks/scirius#31]
Would be also great to have scirius as a Homebrew package for os x.

**Comment by regit** [comment]
I don't have access to macos X and I don't plan to have but we will accept contribution that could allow to do it.

**Comment by Drewshg312** [comment]
I've opened pull request...
Please link to a specific release, e.g. `https://github.com/StamusNetworks/scirius/archive/scirius-1.0.tar.gz`

**Comment by Drewshg312** [comment]
man I'm working on homebrew package... the problem:

    Performing system checks...
    
    System check identified some issues:
    
    WARNINGS:
    rules.Category.created_date: (fields.W161) Fixed default value provided.
    	HINT: It seems you set a fixed date / time / datetime value as default for this field. This may not be what you want. If you want to have the current date as default, use `django.utils.timezone.now`
    rules.SourceAtVersion.updated_date: (fields.W161) Fixed default value provided.
    	HINT: It seems you set a fixed date / time / datetime value as default for this field. This may not be what you want. If you want to have the current date as default, use `django.utils.timezone.now`
    rules.SourceUpdate.created_date: (fields.W161) Fixed default value provided.
    	HINT: It seems you set a fixed date / time / datetime value as default for this field. This may not be what you want. If you want to have the current date as default, use `django.utils.timezone.now`
    
    System check identified 3 issues (0 silenced).
    
    You have unapplied migrations; your app may not work properly until they are applied.
    Run 'python manage.py migrate' to apply them.
    
    July 17, 2015 - 23:53:26
    Django version 1.8.3, using settings 'scirius.settings'
    Starting development server at http://127.0.0.1:8000/
    Quit the server with CONTROL-C.

when doing `python manage.py migrate` getting:

    Traceback (most recent call last):
      File "/usr/local/Cellar/scirius/1.0/libexec/manage.py", line 8, in <module>
        from django.core.management import execute_from_command_line
    ImportError: No module named django.core.management

Any ideas what can cause it?

**Comment by regit** [comment]
It looks like a import issue in django. Something specific to your install. Check your PYTHONPATH variable.

**Comment by regit** [comment]
Did you fix the issue?

**Comment by Drewshg312** [comment]
No but I stuck with homebrew package and guys from Homebrew don't help:
https://github.com/Homebrew/homebrew/pull/41538#issuecomment-122690961
