### ISSUE TITLE
No Suricata events in Scirius

### ISSUE THREAD

**Issue by bugsland** [StamusNetworks/scirius#34]
Hi,

I did reset my SELKS dataset as instructed in a different issue from this forum.
Since I have done that, I can see new events in Kibana, but none in Scirius!

How can I troubleshoot this?

Thanks.
B.

**Comment by bugsland** [comment]
Thanks to Regit for helpling troubleshooting the issue.
This was because I changed my hostname during the SELKS install.
If you do change your hostname, you must then go to scirius -> suricata -> edit
and change the first field "NAME" to match your hostname

**Comment by pevma** [comment]
Just an info note.
Updated the wiki accordingly - 
https://github.com/StamusNetworks/SELKS/wiki/Initial-Setup---HOSTNAME

Thanks
