### ISSUE TITLE
Feature Request: Scirius/Kibana flow

### ISSUE THREAD

**Issue by b-u-g-s** [StamusNetworks/scirius#35]
The flow from Kibana to Scirius works great, you see an alert in Kibana, drill down and eventually ends up in Scirius to see the Suricata Alert. Perfect.

But the other way round is not so perfect.

It is great how Scirius has all those graphs, so you can look at your overall Circle graph from the last x hours and drill down into that graph, you select a category of alerts and can see the details of the Security rule as well as a timeline when that specific rule was triggered and ... that's it!
What is missing is a link back to Kibana so you can see what IP triggered those alerts (would also be great to have that info in Scirius)

At the moment the flow seems to only works one way down (from Kibana to Scirius) and it would be great to have a two way flow!

Thanks.
B.

**Comment by regit** [comment]
Done with kibana 4 so closing.
