### ISSUE TITLE
"Disk" is red - what does that mean?

### ISSUE THREAD

**Issue by Drewshg312** [StamusNetworks/scirius#37]
"Disk" is red - what does that mean?

**Comment by pevma** [comment]
Can you check the available space on your disk ?

**Comment by Drewshg312** [comment]
102.5 Gb available

**Comment by Drewshg312** [comment]
After restart it became yellow and then again red after some time... Is 100Gb not enough???

**Comment by pevma** [comment]
100GB free should definitely be enough (at least for a while , depending on the traffic volume).
Do you have everything in one disk - or is it logically separated ?
Are you using SELKS or just Scirius on some other OS/distro?

**Comment by Drewshg312** [comment]
I'm using Scirius on OS X. Hard disk logically separated… 100 GB on main logical partition (where Scirius is installed)

**Comment by Drewshg312** [comment]
I've noticed that I have scirius.err.log from scirius daemon (67 GB)

**Comment by pevma** [comment]
Anything interesting in it? :)
So do you still have 102Gb free or not?

**Comment by Drewshg312** [comment]
Nothing really interesting... I've removed the log option from the plist
