### ISSUE TITLE
Snort VRT rules update problem

### ISSUE THREAD

**Issue by Drewshg312** [StamusNetworks/scirius#38]
Hi! Tried to add VRT rules as one of my sources:

**Datatype:**

    Signatures files in tar archive
**URI:**

    https://www.snort.org/reg-rules/|snortrules-snapshot.tar.gz|44146283d5bb770b010082666768b9c083bfdb02

When pressed **Update** got this:

![untitled](https://cloud.githubusercontent.com/assets/10493450/8793658/f755cb8e-2f2e-11e5-82eb-5e4cca4881c7.jpg)

**Comment by pevma** [comment]
This is similar to  - https://github.com/StamusNetworks/scirius/issues/27

**Comment by Drewshg312** [comment]
Would be great to have this option in future releases

**Comment by regit** [comment]
Closing as it is a duplicate.

**Comment by regit** [comment]
I've reread this issue and it is not a duplicate. I've also checked the structure of ruleset and it is not really a duplicate on this side.

**Comment by regit** [comment]
I have just pushed a few commits improving error reporting. In your case, it is probable that you get an error from server but it was not displayed correctly. With new version you should see an explicit message.

**Comment by Drewshg312** [comment]
ok! how do I actually upgrade scirius without need to reload all the sources? where does it store them?

**Comment by Drewshg312** [comment]
I've recloned master quickly and tried it again…
![untitled](https://cloud.githubusercontent.com/assets/10493450/9021045/cd61204a-37e3-11e5-823b-d7120f0618a0.jpg)

**Comment by Drewshg312** [comment]
I've tried it again (after discovering this issue:https://github.com/StamusNetworks/scirius/issues/43)
And got this:
![untitled1](https://cloud.githubusercontent.com/assets/10493450/9080330/6c420fc8-3b07-11e5-9bcc-f6ecac626497.jpg)

**Comment by Drewshg312** [comment]
Also tried to update this rule and got:
`Can not fetch data: No connection adapters were found for 'rule_url=https://www.snort.org/reg-rules/|snortrules-snapshot.tar.gz|44116283d5bb170b010082666768b91083bfdb02'`

**Comment by regit** [comment]
You have prefixed with rule_url so it can not work. I have done the test removing it and I've got a 404 instead.
From https://www.snort.org/oinkcodes you should use the following syntax:
https://www.snort.org/rules/<file_name>?oinkcode=<oinkcode>

**Comment by Drewshg312** [comment]
Gotcha! Will try it after https://github.com/StamusNetworks/scirius/issues/43 being fixed…

**Comment by Drewshg312** [comment]
so it adds rules but any time I'm adding new source I get this:
![1](https://cloud.githubusercontent.com/assets/10493450/9107999/2ce7890a-3be0-11e5-8398-4c2965a95dbc.jpg)
![2](https://cloud.githubusercontent.com/assets/10493450/9108001/2eba1e6e-3be0-11e5-93f1-9d0b6696c144.jpg)
![3](https://cloud.githubusercontent.com/assets/10493450/9108007/34a11936-3be0-11e5-9b5a-4f75d5fd1f28.jpg)

**Comment by regit** [comment]
Ok, it may be linked with the git-sources directory not being clean. Could you remove dir in it and reset the app (remove sources or do a full reset).

**Comment by regit** [comment]
By the way, @Drewshg312 please do a git pull before running next tests.

**Comment by Drewshg312** [comment]
`rm -rf git-sources && git pull` and restarting server did not solve the problem - still the same issues

**Comment by regit** [comment]
Do you have any log on console side ? Is suricata binary in the path ? The second message "Error during source update" (should be source testing) could be explained by that.

**Comment by Drewshg312** [comment]
That's what I've got for Community rules:
![1](https://cloud.githubusercontent.com/assets/10493450/9129880/d3e22c22-3c91-11e5-9ff0-e7609f353bfa.jpg)

Then I pressed yellow button and…
![2](https://cloud.githubusercontent.com/assets/10493450/9129881/d7bffc16-3c91-11e5-8b8f-be7da31a5321.jpg)

shell log:

    Quit the server with CONTROL-C.
    /usr/local/lib/python2.7/site-packages/django_tables2/tables.py:178: RemovedInDjango19Warning:     SortedDict is deprecated and will be removed in Django 1.9.
      extra = SortedDict()
    
    [07/Aug/2015 06:06:48]"GET /rules/info?query=disk HTTP/1.1" 200 47
    [07/Aug/2015 06:06:48]"GET /rules/info?query=memory HTTP/1.1" 200 94
    [07/Aug/2015 06:06:48]"GET /rules/info?query=status HTTP/1.1" 200 18
    [07/Aug/2015 06:06:48]"GET /rules/es?query=health HTTP/1.1" 200 349
    [07/Aug/2015 06:06:50]"POST /rules/source/add HTTP/1.1" 200 18303
    [07/Aug/2015 06:06:50]"GET /rules/es?query=health HTTP/1.1" 200 349
    [07/Aug/2015 06:06:50]"GET /rules/es?query=dashboards HTTP/1.1" 200 2
    [07/Aug/2015 06:06:50]"GET /rules/info?query=status HTTP/1.1" 200 18
    [07/Aug/2015 06:06:50]"GET /rules/info?query=memory HTTP/1.1" 200 94
    [07/Aug/2015 06:06:50]"GET /rules/info?query=disk HTTP/1.1" 200 47
    [07/Aug/2015 06:06:53]"GET /rules/source/8/update HTTP/1.1" 200 16
    [07/Aug/2015 06:06:53]"GET /rules/source/8/test HTTP/1.1" 200 302
    [07/Aug/2015 06:07:20]"GET /rules/es?query=health HTTP/1.1" 200 349
    [07/Aug/2015 06:07:20]"GET /rules/info?query=status HTTP/1.1" 200 18
    [07/Aug/2015 06:07:20]"GET /rules/info?query=memory HTTP/1.1" 200 94
    [07/Aug/2015 06:07:20]"GET /rules/info?query=disk HTTP/1.1" 200 47
    [07/Aug/2015 06:07:50]"GET /rules/es?query=health HTTP/1.1" 200 349
    [07/Aug/2015 06:07:50]"GET /rules/info?query=status HTTP/1.1" 200 18
    [07/Aug/2015 06:07:50]"GET /rules/info?query=memory HTTP/1.1" 200 94
    [07/Aug/2015 06:07:50]"GET /rules/info?query=disk HTTP/1.1" 200 47
    /usr/local/lib/python2.7/site-packages/django/utils/datastructures.py:154: RemovedInDjango19Warning: SortedDict is deprecated and will be removed in Django 1.9.
      for key, value in self.items()])

**Comment by Drewshg312** [comment]
This is for VRT:

**Comment by regit** [comment]
So community is OK. Some of the snort rules are not correct so error are not a surprised.
On vrt side, how long does it takes you to download them ? You may exceed the defined timeout.

**Comment by Drewshg312** [comment]
Yeah, takes a few minutes

**Comment by Drewshg312** [comment]
Actually when I create "Suricata" and select all (update, build,push) options, and the output file is set to my suricata rules folder **/usr/local/etc/suricata/rules** it creates not only a **scirius.rules** file but also another **rules** folder inside the **/usr/local/etc/suricata/rules** so like this:
**/usr/local/etc/suricata/rules/rules/**
**/usr/local/etc/suricata/rules/scirius.rules**
Is it normal?

**Comment by Drewshg312** [comment]
And what "push" supposed to do? Restart the daemon? Should it somehow interact with suricata through the unix socket? Or just do something like 'launchctl unload suricata.daemon.plist && launchctl unload suricata.daemon.plist'?

**Comment by regit** [comment]
Yes and no: scirius is not supposed to run as root so it can not restart a service. For that it is using a 'command' file to warn the suri_reloader script that a restart is needed.
In that script you can or use a signal (to trigger a reload of rules) or do a system restart. For now only 'service suricata restart' is run. So you may need to tune/patch this script for MacOSX.
