### ISSUE TITLE
Adding User generates an error

### ISSUE THREAD

**Issue by b-u-g-s** [StamusNetworks/scirius#41]
Hi,

Just tried to add a user to Scirius: Manage Account -> Add 
Username: Report
Password: Password

And I get the following error:

IntegrityError at /accounts/manage/add

NOT NULL constraint failed: auth_user.last_login

Request Method: 	POST
Request URL: 	https://192.168.1.183/accounts/manage/add
Django Version: 	1.8.3
Exception Type: 	IntegrityError
Exception Value: 	

NOT NULL constraint failed: auth_user.last_login

Exception Location: 	/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py in execute, line 318
Python Executable: 	/usr/bin/python
Python Version: 	2.7.9
Python Path: 	

['/usr/local/lib/python2.7/dist-packages/git/ext/gitdb',
 '/opt/selks/scirius',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/gtk-2.0',
 '/usr/lib/pymodules/python2.7',
 '/usr/local/lib/python2.7/dist-packages/gitdb/ext/smmap']

Server time: 	Mon, 27 Jul 2015 15:08:44 +0000

**Comment by regit** [comment]
This is due to a django upgrade. You need to apply the DB migration to be able to use a newer django. usually 
```
python manage.py migrate
```

**Comment by b-u-g-s** [comment]
Thanks Regit, looks my problem is a bit more complicated as there seems to be a bug in Django. 
I will close this issue as this is not directly related to Scirius.
