### ISSUE TITLE
Use SSL with elasticsearch ()

### ISSUE THREAD

**Issue by drew-kun** [StamusNetworks/scirius#42]
I've got this red "Unable to get data from Elasticsearch" message again… I'm using Apache as reverse proxy with ssl between elasticsearch and kibana 4: so the reverse proxy accepts the incoming Elasticsearch requests on port 443 (https) and pushes them to Elasticsearch on port 9200, which is what Elasticsearch is expecting. Part of kibana httpd-vhost:

```
ProxyRequests off
ProxyPass /elasticsearch/ http://127.0.0.1:9200/

 <Location /elasticsearch/>
  ProxyPassReverse /
  SSLRequireSSL
 </Location>
```

in kibana configuration I've changed:
`kibana.elasticsearch_url = kibana.elasticsearch_url || 'http://localhost:9200';`
to
`kibana.elasticsearch_url = kibana.elasticsearch_url || 'https://0.0.0.0/elasticsearch';`
So now all data from E goes to K4 through SSL tunnel (I believe LOL)

I've tried (in **local_settings.py**): `httpS://0.0.0.0/elasticsearch/` - but Scirius don't want to connect through https… 

It would be great to add the possibility of SSL to scirius as another layer of security…

**Comment by regit** [comment]
You need to pass an IP address in `httpS://0.0.0.0/elasticsearch/` It will not work if you put `0.0.0.0` as IP.

**Comment by Drewshg312** [comment]
either way doesn't work. tried:

    https://0.0.0.0/elasticsearch/
    https://192.168.1.51/elasticsearch
    https://127.0.0.1/elasticsearch

**Comment by stamus** [comment]
Hi,

If you can access via localhost the just proxy in http for localhost only.

**Comment by regit** [comment]
If you can access via localhost then just update your proxy config to proxy in http for localhost only.

**Comment by regit** [comment]
Nothing since 3 years so closing.
