### ISSUE TITLE
v1.1 - stable error when adding new source (os x)

### ISSUE THREAD

**Issue by Drewshg312** [StamusNetworks/scirius#43]
When adding new source and pressing "Submit" - getting this:
![untitled](https://cloud.githubusercontent.com/assets/10493450/9079352/0dc320b2-3afe-11e5-8de5-2595c4ef26d8.jpg)
but when pressing "go back" browser button it says that this rule already exists (so it actually creates the rule and after that gives an error...

**Comment by regit** [comment]
Hi,

It is supposed to be fixed by https://github.com/StamusNetworks/scirius/commit/f8c5b8486e0ba6521b3bb6584293fb7838627ff7. From line number it seems you are not using the latest version. Can you check this please ?

**Comment by Drewshg312** [comment]
sorry could you tell me how can I check? I'm new to git...

**Comment by Drewshg312** [comment]
'About' tab says v1.1

**Comment by regit** [comment]
If you have run a 'git clone' to create the directory of sicirius, the run 'git pull' to update the source

**Comment by Drewshg312** [comment]
Well after doing:

    $ cd /usr/local/var/www/scirius
    $ git pull

instead of "login page" I'm getting this:
![1](https://cloud.githubusercontent.com/assets/10493450/9092653/428a7a12-3b5c-11e5-88c4-519a2b030725.jpg)
I've tried it two times and seems like your last commits broke everything... lol
Now I can't even use it))

**Comment by regit** [comment]
It did not break anything, you just need to migrate the db via django utilities :)

**Comment by Drewshg312** [comment]
but it didn't say to run "migrate"…

    $ /usr/local/bin/python /usr/local/var/www/scirius/manage.py runserver
    /usr/local/lib/python2.7/site-packages/django_tables2/tables.py:175: RemovedInDjango19Warning: SortedDict is deprecated and will be removed in Django 1.9.
      attrs["base_columns"] = SortedDict(parent_columns)
    
    /usr/local/lib/python2.7/site-packages/django_tables2/tables.py:197: RemovedInDjango19Warning: SortedDict is deprecated and will be removed in Django 1.9.
      attrs["base_columns"].update(SortedDict(cols))
    
    /usr/local/lib/python2.7/site-packages/django_tables2/tables.py:175: RemovedInDjango19Warning: SortedDict is deprecated and will be removed in Django 1.9.
      attrs["base_columns"] = SortedDict(parent_columns)
    
    /usr/local/lib/python2.7/site-packages/django_tables2/tables.py:197: RemovedInDjango19Warning: SortedDict is deprecated and will be removed in Django 1.9.
      attrs["base_columns"].update(SortedDict(cols))
    
    Performing system checks...
    
    System check identified no issues (0 silenced).
    August 05, 2015 - 17:35:58
    Django version 1.8, using settings 'scirius.settings'
    Starting development server at http://127.0.0.1:8000/
    Quit the server with CONTROL-C.

**Comment by regit** [comment]
Yes, git pull and now it should say it ;)

**Comment by Drewshg312** [comment]
I ran migrate:

    $ python manage.py migrate

and then restarted the server - got the same error in browser and this in the shell:

    Quit the server with CONTROL-C.
    [05/Aug/2015 17:40:40]"GET / HTTP/1.1" 302 0
    /usr/local/lib/python2.7/site-packages/django_tables2/tables.py:178: RemovedInDjango19Warning: SortedDict is deprecated and will be removed in Django 1.9.
      extra = SortedDict()
    
    [05/Aug/2015 17:40:40]"GET /accounts/login/ HTTP/1.1" 500 176421

**Comment by regit** [comment]
For info, till now only south based migration were commited. I've now added the migration for django > 1.7.

**Comment by regit** [comment]
During migrate you should see something like:
```
eric@ice-age2:~/git/stamus/scirius (master)$ python manage.py migrate
Operations to perform:
  Synchronize unmigrated apps: suricata, accounts, django_tables2, bootstrap3
  Apply all migrations: admin, rules, contenttypes, auth, sessions
Synchronizing apps without migrations:
  Creating tables...
  Installing custom SQL...
  Installing indexes...
Running migrations:
  Applying rules.0039_auto_20150805_1737... OK
```

**Comment by Drewshg312** [comment]
so what should I do now? 
    $ git pull && python manage.py migrate
?

**Comment by regit** [comment]
yes, update the code, then run migration

**Comment by Drewshg312** [comment]
done it and still got:

    You have unapplied migrations; your app may not work properly until they are applied.
    Run 'python manage.py migrate' to apply them.
    
    August 05, 2015 - 17:48:46
    Django version 1.8, using settings 'scirius.settings'
    Starting development server at http://127.0.0.1:8000/
    Quit the server with CONTROL-C.

done it two times

**Comment by Drewshg312** [comment]
migration output:

    $ python manage.py migrate
    /usr/local/lib/python2.7/site-packages/django_tables2/tables.py:175: RemovedInDjango19Warning: SortedDict is deprecated and will be removed in Django 1.9.
      attrs["base_columns"] = SortedDict(parent_columns)
    
    /usr/local/lib/python2.7/site-packages/django_tables2/tables.py:197: RemovedInDjango19Warning: SortedDict is deprecated and will be removed in Django 1.9.
      attrs["base_columns"].update(SortedDict(cols))
    
    Operations to perform:
      Synchronize unmigrated apps: staticfiles, suricata, messages, accounts, django_tables2, revproxy, bootstrap3
      Apply all migrations: admin, rules, contenttypes, auth, sessions
    Synchronizing apps without migrations:
      Creating tables...
        Running deferred SQL...
      Installing custom SQL...
    Running migrations:
      Rendering model states... DONE
      Applying rules.0001_initial...Traceback (most recent call last):
      File "manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
      File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
        utility.execute()
      File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
        self.execute(*args, **cmd_options)
      File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
        output = self.handle(*args, **options)
      File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 221, in handle
        executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
      File "/usr/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
        self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
      File "/usr/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 147, in apply_migration
        state = migration.apply(state, schema_editor)
      File "/usr/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 115, in apply
        operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
      File "/usr/local/lib/python2.7/site-packages/django/db/migrations/operations/models.py", line 59, in database_forwards
        schema_editor.create_model(model)
      File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 282, in create_model
        self.execute(sql, params or None)
      File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 107, in execute
        cursor.execute(sql, params)
      File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
        return super(CursorDebugWrapper, self).execute(sql, params)
      File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
        return self.cursor.execute(sql, params)
      File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
        six.reraise(dj_exc_type, dj_exc_value, traceback)
      File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
        return self.cursor.execute(sql)
      File "/usr/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 316, in execute
        return Database.Cursor.execute(self, query)
    django.db.utils.OperationalError: table "rules_category" already exists
    
    Andryuwka @ drew-sh.server:/usr/local/var/www/scirius1.0 (16 entries, 0 hidden)
    #521 Wed Aug 05 10:48:33 $ /usr/local/bin/python /usr/local/var/www/scirius1.0/manage.py runserver
    /usr/local/lib/python2.7/site-packages/django_tables2/tables.py:175: RemovedInDjango19Warning: SortedDict is deprecated and will be removed in Django 1.9.
      attrs["base_columns"] = SortedDict(parent_columns)
    
    /usr/local/lib/python2.7/site-packages/django_tables2/tables.py:197: RemovedInDjango19Warning: SortedDict is deprecated and will be removed in Django 1.9.
      attrs["base_columns"].update(SortedDict(cols))
    
    /usr/local/lib/python2.7/site-packages/django_tables2/tables.py:175: RemovedInDjango19Warning: SortedDict is deprecated and will be removed in Django 1.9.
      attrs["base_columns"] = SortedDict(parent_columns)
    
    /usr/local/lib/python2.7/site-packages/django_tables2/tables.py:197: RemovedInDjango19Warning: SortedDict is deprecated and will be removed in Django 1.9.
      attrs["base_columns"].update(SortedDict(cols))
    
    Performing system checks...
    
    System check identified no issues (0 silenced).

**Comment by regit** [comment]
OK, looks like starting from scratch (remove db file) would be the easier method as migration where not included :/

**Comment by Drewshg312** [comment]
could you please be more precise what should I do step by step

**Comment by regit** [comment]
This procedure will loose your data:
```
rm db.sqlite3
python manage.py syncdb
python manage.py migrate
```

**Comment by Drewshg312** [comment]
Ok. Seems like everything works now, so this should be closed but there are some troubles with VRT and Community rules and not only them... I'll explain here https://github.com/StamusNetworks/scirius/issues/38
