### ISSUE TITLE
Can't create "suricata" instance in scirius (OS X)

### ISSUE THREAD

**Issue by Drewshg312** [StamusNetworks/scirius#44]
Hi. So I've added all sources I wanted (VRT, Community, EmergingThreats...), Created ruleset and when trying to create new Suricata instance got this when pressed "Submit":

![1](https://cloud.githubusercontent.com/assets/10493450/9262064/02da240a-41c7-11e5-8260-1e1783868dcb.jpg)

So I can't use scirius..

**Comment by regit** [comment]
Hi,

Try to restart scirius, then recreate the ruleset. If it works then you possibly had one "background" task stuck.

**Comment by Drewshg312** [comment]
Thanx it worked...
