### ISSUE TITLE
New Suricata stats in Scirius - Hyperlink request

### ISSUE THREAD

**Issue by b-u-g-s** [StamusNetworks/scirius#45]
Hi,

Really like the new stats you have added in Scirius.
I was a bit confused at first where to look, and found those stats under the Suricata tab.
Would be nice to also have an hyper link menu to those stats on the LEFT Menu of Scirius showing the Green/Amber/Red status for disk/memory.

Also, is there any info you could provide for some disk related status?

especially if it helps understanding why an indicator gets anything but a green color!
Usage will tell, but I wonder next time I get an amber for memory, will I understand why this happens by looking at the new Suricata Memory stats?
B.

**Comment by regit** [comment]
Really interesting I will have a look to that.
