### ISSUE TITLE
Can't update suricata ruleset

### ISSUE THREAD

**Issue by drew-kun** [StamusNetworks/scirius#51]
Hi!
Today tried to update my ruleset which contains of **Community+VRT+ETO+SSLBL_Abuse.ch** rules...
Went to **Suricata** tab selected **Update** and pressed **Apply** and got this error 502:

![2](https://cloud.githubusercontent.com/assets/10493450/9537431/d834c846-4cec-11e5-961a-86b1adb67400.jpg)

not sure if it's connected to the problem but when I go to **Rulesets** tab and click on my actual ruleset, I see this at the bottom:

![1](https://cloud.githubusercontent.com/assets/10493450/9537462/34621e0c-4ced-11e5-9baa-d69a015f6e9d.jpg)

What does that mean and why can't I update my rules?

**Comment by regit** [comment]
There is two different things here:
* the 502 error: if I remember correctly you are proxying the connection to scirius. Here you ask an update with a volume of data to fetch which is huge. So it takes time and the reverse proxy timeout. You may need to improve your reverse proxy configuration.
* Ruleset has errors: is Suricata in the binary path of Scirius? Scirius needs to be able to start suricata in testing mode to check validity. You can test this by going to a single rule page, it will display the validity of the rule using the same testing mechanism. If it fails the same way then this should be the mistake.

**Comment by Drewshg312** [comment]
well let's try to figure out all issues one by one… first with proxy:
my apache vhost **scirius.conf:**

    <VirtualHost *:8443>
        ServerAdmin admin@localhost
        ServerName www.server.scirius
        ServerAlias server.scirius
        ErrorLog /usr/local/var/log/apache2/scirius_error.log
        LogLevel warn
        CustomLog /usr/local/var/log/apache2/scirius_access.log combined
        ###-- SSL Certificates --###
        SSLProxyEngine on
        SSLCertificateFile "/usr/local/etc/apache2/2.4/ssl-keys/ssl_server.crt"
        SSLCertificateKeyFile "/usr/local/etc/apache2/2.4/ssl-keys/ssl_server.key"
        SetEnvIf User-Agent ".*MSIE.*" nokeepalive ssl-unclean-shutdown
        CustomLog /usr/local/var/log/apache2/scirius_ssl_request.log \
        "%t %h %{SSL_PROTOCOL}x %{SSL_CIPHER}x \"%r\" %b"
        ##### -- PROXY -- #####
        ProxyRequests Off
        <Location />
            ProxyPassReverse /
            SSLRequireSSL
        </Location>
        <Proxy *>
            Order Allow,Deny
            Allow from all
            Options -MultiViews
        </Proxy>
            ProxyPass / https://127.0.0.1:8000
            ProxyPassReverse / https://127.0.0.1:8000
            RewriteEngine on
            RewriteCond %{DOCUMENT_ROOT}/%{REQUEST_FILENAME} !-f
            RewriteRule .* http://127.0.0.1:8000%{REQUEST_URI} [P,QSA]
    </VirtualHost>

my **local_settings.py:**

    # Elastic search
    # for using Apache SSL Tunnel from Elasticsearch to Scirius:
    #ELASTICSEARCH_ADDRESS = "https://127.0.0.1/elasticsearch"
    ELASTICSEARCH_LOGSTASH_INDEX = "logstash-*"
    
    # Kibana
    USE_KIBANA = True
    # Use django as a reverse proxy for kibana request
    # This will allow you to use scirius authentication to control
    # access to Kibana
    KIBANA_PROXY = False
    # Kibana URL
    KIBANA_URL = "https://www.server.kibana"
    # Kibana index name
    KIBANA_INDEX = ".kibana"
    # Kibana version
    KIBANA_VERSION = 4

Any suggestions why do I get this behavior?

**Comment by regit** [comment]
Hi,

I was thinking about http://httpd.apache.org/docs/2.2/mod/mod_proxy.html#proxytimeout

**Comment by Drewshg312** [comment]
Hi so I've tried to add `ProxyTimeout 300` to my scirius virtual host and got this:

![1](https://cloud.githubusercontent.com/assets/10493450/9645072/6c6b9aae-517e-11e5-87c0-dd790dd18b6d.jpg)
