### ISSUE TITLE
Deleting sources

### ISSUE THREAD

**Issue by kevross33** [StamusNetworks/scirius#58]
Hi,

When trying to delete a source from the web interface I get the following error:

SourceAtVersion matching query does not exist.
Request Method:	POST
Request URL:	http://10.8.117.60:8000/rules/source/3/delete
Django Version:	1.8.6
Exception Type:	DoesNotExist
Exception Value:	
SourceAtVersion matching query does not exist.
Exception Location:	/usr/lib/python2.7/site-packages/django/db/models/query.py in get, line 334
Python Executable:	/usr/bin/python
Python Version:	2.7.5
Python Path:	
['/usr/lib/python2.7/site-packages/git/ext/gitdb',
 '/etc/suricata/Scirius',
 '/usr/lib/python2.7/site-packages/volatility-2.4-py2.7.egg',
 '/usr/lib64/python27.zip',
 '/usr/lib64/python2.7',
 '/usr/lib64/python2.7/plat-linux2',
 '/usr/lib64/python2.7/lib-tk',
 '/usr/lib64/python2.7/lib-old',
 '/usr/lib64/python2.7/lib-dynload',
 '/usr/lib64/python2.7/site-packages',
 '/usr/lib/python2.7/site-packages',
 '/usr/lib64/python2.7/site-packages/gitdb/ext/smmap']

**Comment by pevma** [comment]
I just tried deleting a source and did not manage to reproduce the issue.
Could you please list detailed steps of how to reproduce?

**Comment by yehias** [comment]
hey I have same issue the issue exactly due to the wrong data signature type which make scirius to crash but I didn't figure out how to remove it

**Comment by pevma** [comment]
How do you mean "wrong data signature type"? What are the steps that we can reproduce that issue?

**Comment by regit** [comment]
Fix in progress. I'm gonna commit it this afternoon.

**Comment by regit** [comment]
Fixed this issue and the lack of error reporting pointed out by @yehias

**Comment by yehias** [comment]
Sorry for late reply if you upload customized signatures or snort modified
will make This error so I saw that it fixed already so can you explain how?
I need to delete it manually I think from nginx but I can't figure out how

**Comment by regit** [comment]
You can now delete "incomplete" sources where the parsing has failed after creation. In your case, you need to delete sources already created. You can do it the usual way by going to 'Sources->click on a source in table->delete in side bar'

**Comment by yehias** [comment]
Already knew that simply when you did that you will get the error
