### ISSUE TITLE
auto update sid-msg.map

### ISSUE THREAD

**Issue by mobidevadmin** [StamusNetworks/scirius#62]
Hello,

you are doing a great job, guys! 

I'm missing sid-msg.map re-generation option along with restarting suricata. Here is a use case:
- when some rulesets getting update, new rules ID appear and one need to regenerate sid-msg.map in order to see descriptions in one's favourite interface.
- when you add new rulesets, you need to re-generate sig-msg.map

Usually, i use oinkmaster issuing such command and restart suricata again.
/usr/share/oinkmaster/create-sidmap.pl /etc/suricata/rules/ > /etc/suricata/rules/sid-msg.map

Would be nice to see such option in future releases!

**Comment by pevma** [comment]
This would be the case of a "manual" ruleset generation.
Otherwise each ruleset should come (or provides) the sig-msg.map that Scirius should make use of example - 
http://rules.emergingthreats.net/open/suricata/
