### ISSUE TITLE
suri_reloader sometimes doesn't restart suricata

### ISSUE THREAD

**Issue by mobidevadmin** [StamusNetworks/scirius#67]
Hello,

sometimes while scirius restarts suricata, suricata doesn't start even though log file shows that it has been started and .pid file isn't empty. But, in fact, there is no such process running.
Can't reproduce it as it happens from time to time. 
Please, ask me questions in order to narrow down this issue.

**Comment by pevma** [comment]
Can you tell if Suricata does not start because there is a pid file already ?(can that be the reason?)

**Comment by mobidevadmin** [comment]
Hello pevma,

Unlikely as according to log file it starts properly. Even though it could be suricata 3.0 issue, cause i started facing this issue only when i upgraded suricata, i haven't faced this issue when i do sighup by logrotate procedure

**Comment by pevma** [comment]
Hi,

Ok. Have you ever experienced the same when doing just regular
> service suricata restart 
?

**Comment by mobidevadmin** [comment]
Hi,

never experienced this before by issuing
service suricata restart

I've done it only 3 or 4 times for the last couple month, though.

**Comment by pevma** [comment]
When  that happens through restarting suri through Scirius - if you redo the process would it restart correctly or manual intervention is required to restart Suricata?

**Comment by mobidevadmin** [comment]
The situation with Suricata "false starting" happens from time to time. Once i catch this issue again, i'll try this out.
Thanks

**Comment by pevma** [comment]
ok - please keep us posted.
Thank you

**Comment by mobidevadmin** [comment]
Hello,

please close the ticket as it hasn't happened since the last post.
