### ISSUE TITLE
rules parse errors don't update

### ISSUE THREAD

**Issue by mobidevadmin** [StamusNetworks/scirius#68]
Hi,

seems that parse errors don't update on each ruleset reload procedure. 

https://gyazo.com/630041031a49e6a8537248e98522b4e2
https://gyazo.com/1452e76b7ff244431882439a90916187

**Comment by regit** [comment]
Ok, finally understood your issue. I'm gonna try a fix.

**Comment by regit** [comment]
Just pushed an update for that issue. It was more intrusive than I initially thought.

**Comment by regit** [comment]
0535c13 is completing this. Closing the issue.

**Comment by mobidevadmin** [comment]
Thanks for the update,

though after this update i've got this error

http://dpaste.com/0WBHSFE

**Comment by regit** [comment]
@mobidevadmin please run `python manage.py migrate` and it you suricata.yaml configuration file is not in the standard place (relatively to the rules dir) then Do Suricata->Edit.

**Comment by mobidevadmin** [comment]
Hi regit,

thanks for your help. It works now. Is this step mentioned in some doc, so i should have checked it first in order not to bother you much?

**Comment by regit** [comment]
Humm good point we are missing wiki page for running it from git...

**Comment by mobidevadmin** [comment]
Hello regit,

could you please help with following issue
https://gyazo.com/658fb599569fa083cf259e4773751487 - Ruleset status "Uknown"
https://gyazo.com/f42b99b9adea2c2570e724949c08b750

Should i take an extra action?

**Comment by regit** [comment]
What configuration file are you using ? Is it correctly setup in Suricata->Edit ?

**Comment by regit** [comment]
OK, my bad, my test setup did not reload correctly the code so everything was broken.

@mobidevadmin can you update git and retry ?

**Comment by regit** [comment]
3949e37def6bc7778a09a2b1788b5092070bd2de is fixing another related issue.

**Comment by mobidevadmin** [comment]
I've updated the code, ran manage.py makemigrations and reran python manage.py migrate. And nothing changed.
I'm using suricata configuration file located in /etc/suricata/suricata.yaml which is default location for ubuntu installation

**Comment by regit** [comment]
When you are on ruleset page can you add `test` at the end of the uri and paste here the result ?

**Comment by mobidevadmin** [comment]
Environment:


Request Method: GET
Request URL: http://scirius.local.mobi-dev.com/rules/ruleset/1/test

Django Version: 1.8
Python Version: 2.7.6
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django_tables2',
 'bootstrap3',
 'rules',
 'suricata',
 'accounts')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'scirius.loginrequired.LoginRequiredMiddleware',
 'scirius.utils.TimezoneMiddleware')


Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/opt/scirius/rules/views.py" in test_ruleset
  646.     return HttpResponse(json.dumps(ruleset.test()), content_type="application/json")
File "/opt/scirius/rules/models.py" in test
  818.         result = self.test_rule_buffer(rule_buffer)
File "/opt/scirius/rules/models.py" in test_rule_buffer
  813.             return testor.rules(rule_buffer, related_files = related_files)
File "/opt/scirius/suricata/common.py" in rules
  278.             config_buffer = self.get_system_config_buffer()
File "/opt/scirius/suricata/common.py" in get_system_config_buffer
  255.             with open(self.yaml_file, 'r') as cf:

Exception Type: AttributeError at /rules/ruleset/1/test
Exception Value: Test instance has no attribute 'yaml_file'

**Comment by regit** [comment]
Ok, you are not running the latest version.

**Comment by mobidevadmin** [comment]
the latest commit i've got in my version

commit 3949e37def6bc7778a09a2b1788b5092070bd2de
Author: Eric Leblond <eric@regit.org>
Date:   Tue Mar 15 14:11:25 2016 +0100

    rules: ruleset needs test after adding a source

**Comment by regit** [comment]
Did you restart scirius ?

**Comment by mobidevadmin** [comment]
yes, it's been restarted.

**Comment by regit** [comment]
Can you remove *.pyc file, it really should not show the code you have in the traceback.

**Comment by mobidevadmin** [comment]
should i remove all of them? As there are lots of them.

**Comment by regit** [comment]
yes please

**Comment by regit** [comment]
rhaaa I need a break. I've missed something once again. Really sorry. Pushing a fix.

**Comment by mobidevadmin** [comment]
:) ok, waiting for the fix, then

**Comment by regit** [comment]
It should be fixed now.

**Comment by mobidevadmin** [comment]
Hello regit,
it works at first glance. Will check more precisely and let you know.

**Comment by mobidevadmin** [comment]
so far so good, i think the issue could be closed now. 

Thanks!

**Comment by regit** [comment]
great!
