### ISSUE TITLE
No superuser created

### ISSUE THREAD

**Issue by ejectck** [StamusNetworks/scirius#70]
Installing on FreeBSD 10.1 with python27 and MySQL database.

I created database scirius and granted permissions to scirius user on localhost.

I created my.cnf in scirius root

```
cat  my.cnf
[client]
database = scirius
user = scirius
password = scirius
default-character-set = utf8
```

Then I and changed settings.py to:

```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
          'OPTIONS': {
            'read_default_file': '/appdata/nsm/scirius/my.cnf',
        },
    }
}
```

`python manage.py syncdb`
it runs (I see tables created in MySQL database) and then stops at:
`You have installed Django's auth system, and don't have any superusers defined.`
I press CTRL+C after 10 minutes of waiting.

When I checked MySQL table with mysql scirius -e "select \* from auth_user" I see it's empty.

I tried to use createuser command, but it fails (running from bash):

```
python manage.py createsuperuser
Superuser creation skipped due to not running in a TTY. You can run `manage.py createsuperuser` in your project to create one manually.
```

**Comment by regit** [comment]
Createsuperuser is the original command from Django. So if it fails, it is more a Django issue than a scirius one. http://stackoverflow.com/questions/32532900/not-able-to-create-super-user-with-django-manage-py is the same issue. Are you running it in a real terminal ? Password settings needs that.
