### ISSUE TITLE
scirius open page spams web server with requests

### ISSUE THREAD

**Issue by mobidevadmin** [StamusNetworks/scirius#72]
Hello,

we have scirius page opened permanently and sometimes it causes scirius to spam web server with tons of requests causing the server to die under sort of DOS attack and web browser to consume lots of CPU. Refreshing page or switching to another tab within scirius web page solves the problem. Here are some samples of requests:

`scirius.*******:80 ***.***.***.*** - - [22/Apr/2016:10:53:42 +0300] "GET /rules/info?query=disk HTTP/1.1" 200 310 "http://scirius.*******/rules/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
scirius.*******:80 ***.***.***.*** - - [22/Apr/2016:10:53:42 +0300] "GET /rules/info?query=status HTTP/1.1" 200 279 "http://scirius.*******/rules/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
scirius.*******:80 ***.***.***.*** - - [22/Apr/2016:10:53:42 +0300] "GET /rules/info?query=memory HTTP/1.1" 200 362 "http://scirius.*******/rules/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
scirius.*******:80 ***.***.***.*** - - [22/Apr/2016:10:53:42 +0300] "GET /rules/info?query=status HTTP/1.1" 200 279 "http://scirius.*******/rules/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
scirius.*******:80 ***.***.***.*** - - [22/Apr/2016:10:53:42 +0300] "GET /rules/info?query=disk HTTP/1.1" 200 310 "http://scirius.*******/rules/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
scirius.*******:80 ***.***.***.*** - - [22/Apr/2016:10:53:42 +0300] "GET /rules/info?query=memory HTTP/1.1" 200 362 "http://scirius.*******/rules/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
scirius.*******:80 ***.***.***.*** - - [22/Apr/2016:10:53:43 +0300] "GET /rules/info?query=disk HTTP/1.1" 200 310 "http://scirius.*******/rules/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
scirius.*******:80 ***.***.***.*** - - [22/Apr/2016:10:53:43 +0300] "GET /rules/info?query=memory HTTP/1.1" 200 362 "http://scirius.*******/rules/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
scirius.*******:80 ***.***.***.*** - - [22/Apr/2016:10:53:43 +0300] "GET /rules/info?query=disk HTTP/1.1" 200 310 "http://scirius.*******/rules/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
scirius.*******:80 ***.***.***.*** - - [22/Apr/2016:10:53:43 +0300] "GET /rules/info?query=memory HTTP/1.1" 200 362 "http://scirius.*******/rules/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"

or

scirius.*******:80 ***.***.***.*** - - [20/Apr/2016:16:47:43 +0300] "GET /rules/info HTTP/1.1" 200 252 "http://scirius.*******/rules/rule/pk/2022722/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36"
scirius.*******:80 ***.***.***.*** - - [20/Apr/2016:16:47:43 +0300] "GET /rules/info HTTP/1.1" 200 252 "http://scirius.*******/rules/rule/pk/2022722/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36"
scirius.*******:80 ***.***.***.*** - - [20/Apr/2016:16:47:43 +0300] "GET /rules/info HTTP/1.1" 200 252 "http://scirius.*******/rules/rule/pk/2022722/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36"
scirius.*******:80 ***.***.***.*** - - [20/Apr/2016:16:47:46 +0300] "GET /rules/info HTTP/1.1" 200 252 "http://scirius.*******/rules/rule/pk/2022722/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36"
scirius.*******:80 ***.***.***.*** - - [20/Apr/2016:16:47:43 +0300] "GET /rules/info HTTP/1.1" 200 252 "http://scirius.*******/rules/rule/pk/2022722/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36"
scirius.*******:80 ***.***.***.*** - - [20/Apr/2016:16:47:46 +0300] "GET /rules/info HTTP/1.1" 200 252 "http://scirius.*******/rules/rule/pk/2022722/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36"
scirius.*******:80 ***.***.***.*** - - [20/Apr/2016:16:47:46 +0300] "GET /rules/info HTTP/1.1" 200 252 "http://scirius.*******/rules/rule/pk/2022722/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36"
scirius.*******:80 ***.***.***.*** - - [20/Apr/2016:16:47:46 +0300] "GET /rules/info HTTP/1.1" 200 252 "http://scirius.*******/rules/rule/pk/2022722/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36"
scirius.*******:80 ***.***.***.*** - - [20/Apr/2016:16:47:46 +0300] "GET /rules/info HTTP/1.1" 200 252 "http://scirius.*******/rules/rule/pk/2022722/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36"
scirius.*******:80 ***.***.***.*** - - [20/Apr/2016:16:47:46 +0300] "GET /rules/info HTTP/1.1" 200 252 "http://scirius.*******/rules/rule/pk/2022722/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36"
scirius.*******:80 ***.***.***.*** - - [20/Apr/2016:16:47:43 +0300] "GET /rules/info HTTP/1.1" 200 252 "http://scirius.*******/rules/rule/pk/2022722/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36"
`

This happens for Ubuntu Linux 14.04 LTS and Chrome/Firefox. We haven't tested this neither on other web browsers nor on other OSs

**Comment by stamus** [comment]
Hi,
Are you using 1.1.6 ? It is fixing a few problems related to the issue you reported. But some may remains.
Le 22 avr. 2016 5:38 PM, mobidevadmin <notifications@github.com> a écrit :Hello,

we have scirius page opened permanently and sometimes it causes scirius to spam web server with tons of requests causes the server to die under sort of DOS attack and web browser to consume lots of CPU. Refreshing page or switching to another tab within scirius web page solves the problem. Here are some samples of requests:

`scirius.******:80 *...** - - [22/Apr/2016:10:53:42 +0300] "GET /rules/info?query=disk HTTP/1.1" 200 310 "http://scirius.*******/rules/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
scirius.******:80 *...** - - [22/Apr/2016:10:53:42 +0300] "GET /rules/info?query=status HTTP/1.1" 200 279 "http://scirius.*******/rules/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
scirius.******:80 *...** - - [22/Apr/2016:10:53:42 +0300] "GET /rules/info?query=memory HTTP/1.1" 200 362 "http://scirius.*******/rules/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
scirius.******:80 *...** - - [22/Apr/2016:10:53:42 +0300] "GET /rules/info?query=status HTTP/1.1" 200 279 "http://scirius.*******/rules/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
scirius.******:80 *...** - - [22/Apr/2016:10:53:42 +0300] "GET /rules/info?query=disk HTTP/1.1" 200 310 "http://scirius.*******/rules/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
scirius.******:80 *...** - - [22/Apr/2016:10:53:42 +0300] "GET /rules/info?query=memory HTTP/1.1" 200 362 "http://scirius.*******/rules/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
scirius.******:80 *...** - - [22/Apr/2016:10:53:43 +0300] "GET /rules/info?query=disk HTTP/1.1" 200 310 "http://scirius.*******/rules/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
scirius.******:80 *...** - - [22/Apr/2016:10:53:43 +0300] "GET /rules/info?query=memory HTTP/1.1" 200 362 "http://scirius.*******/rules/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
scirius.******:80 *...** - - [22/Apr/2016:10:53:43 +0300] "GET /rules/info?query=disk HTTP/1.1" 200 310 "http://scirius.*******/rules/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
scirius.******:80 *...** - - [22/Apr/2016:10:53:43 +0300] "GET /rules/info?query=memory HTTP/1.1" 200 362 "http://scirius.*******/rules/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"

or

scirius.******:80 *...** - - [20/Apr/2016:16:47:43 +0300] "GET /rules/info HTTP/1.1" 200 252 "http://scirius.*******/rules/rule/pk/2022722/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36"
scirius.******:80 *...** - - [20/Apr/2016:16:47:43 +0300] "GET /rules/info HTTP/1.1" 200 252 "http://scirius.*******/rules/rule/pk/2022722/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36"
scirius.******:80 *...** - - [20/Apr/2016:16:47:43 +0300] "GET /rules/info HTTP/1.1" 200 252 "http://scirius.*******/rules/rule/pk/2022722/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36"
scirius.******:80 *...** - - [20/Apr/2016:16:47:46 +0300] "GET /rules/info HTTP/1.1" 200 252 "http://scirius.*******/rules/rule/pk/2022722/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36"
scirius.******:80 *...** - - [20/Apr/2016:16:47:43 +0300] "GET /rules/info HTTP/1.1" 200 252 "http://scirius.*******/rules/rule/pk/2022722/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36"
scirius.******:80 *...** - - [20/Apr/2016:16:47:46 +0300] "GET /rules/info HTTP/1.1" 200 252 "http://scirius.*******/rules/rule/pk/2022722/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36"
scirius.******:80 *...** - - [20/Apr/2016:16:47:46 +0300] "GET /rules/info HTTP/1.1" 200 252 "http://scirius.*******/rules/rule/pk/2022722/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36"
scirius.******:80 *...** - - [20/Apr/2016:16:47:46 +0300] "GET /rules/info HTTP/1.1" 200 252 "http://scirius.*******/rules/rule/pk/2022722/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36"
scirius.******:80 *...** - - [20/Apr/2016:16:47:46 +0300] "GET /rules/info HTTP/1.1" 200 252 "http://scirius.*******/rules/rule/pk/2022722/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36"
scirius.******:80 *...** - - [20/Apr/2016:16:47:46 +0300] "GET /rules/info HTTP/1.1" 200 252 "http://scirius.*******/rules/rule/pk/2022722/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36"
scirius.******:80 *...** - - [20/Apr/2016:16:47:43 +0300] "GET /rules/info HTTP/1.1" 200 252 "http://scirius.*******/rules/rule/pk/2022722/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36"
`

This happens for Ubuntu Linux 14.04 LTS and Chrome/Firefox. We haven't tested this neither on other web browsers nor on other OSs

**Comment by mobidevadmin** [comment]
Hi Stamus,

Here is what i've got on scirius start after pulling the code in order to obtain the latest version 

/usr/local/lib/python2.7/dist-packages/django_tables2/tables.py:175: RemovedInDjango19Warning: SortedDict is deprecated and will be removed in Django 1.9.
  attrs["base_columns"] = SortedDict(parent_columns)

/usr/local/lib/python2.7/dist-packages/django_tables2/tables.py:197: RemovedInDjango19Warning: SortedDict is deprecated and will be removed in Django 1.9.
  attrs["base_columns"].update(SortedDict(cols))

Traceback (most recent call last):
  File "/opt/scirius/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named dbbackup

**Comment by mobidevadmin** [comment]
Hi stamus,

I've updated to the latest version. Will reopen the ticket in case I face again this issue as it occurs sporadically

**Comment by mobidevadmin** [comment]
Hi there,

the issue is still persist for v. 1.1.7

**Comment by regit** [comment]
I've got a setup where it shows up. Working on a fix.

**Comment by regit** [comment]
https://github.com/StamusNetworks/scirius/commit/e1ac10755da4165429c7b0639ef84783da9d5830 should fix the problem. At least it does it here. @mobidevadmin can you try to use latest git ?

**Comment by mobidevadmin** [comment]
Hi regit,

got the latest update. Leaving it open for the next few days. If it doesn't appear, i'll close the ticket

**Comment by regit** [comment]
ok, perfect.

**Comment by mobidevadmin** [comment]
regit,

the issue still occurs

**Comment by regit** [comment]
@mobiledevadmin, did you restart the browser or at least reload the page ? (Stupid question first). If it is the case then can you check the sequence of requests to see if it is the same ?

**Comment by mobidevadmin** [comment]
regit,

I believe I did reload the page or even more restarted the browser. The scirius was sending /rules/info URI.
But don't jump the gun then as I'm not 100% sure in neither in reloading page nor in restarting browser after update

**Comment by mobidevadmin** [comment]
regit,

I believe I did reload the page or even more restarted the browser. The scirius was sending /rules/info URI.
But don't jump the gun then as I'm not 100% sure in neither in reloading page nor in restarting browser after update

**Comment by regit** [comment]
ok, please also check the rate of requests. We should see the same one used but at a lower rate (around 5 request every 30 seconds per client).

**Comment by mobidevadmin** [comment]
now it's 3 requests per 30 seconds for Home page. One per each metric - memory, status, disk

**Comment by regit** [comment]
Ok, that is what is expected. Please close the ticket once you've seen it remains stable other a long period.

**Comment by regit** [comment]
No update since 30 days, so closing.
