### ISSUE TITLE
Multi-probe ruleset generator

### ISSUE THREAD

**Issue by arktronic** [StamusNetworks/scirius#74]
Hello,

I'd like to develop a ruleset generator that can create multiple rule outputs for different probes. It looks like this can be best accomplished by creating an additional Django app in the existing Scirius project and using the `RULESET_MIDDLEWARE` setting to switch between the current "suricata" one and the new one.

Would you consider merging such a change with Scirius once it is developed? 

Thank you,
Sasha

**Comment by regit** [comment]
Hello, this is already part of Scirius Enterprise so we are not planning to do it and we may not merge it if available.
