### ISSUE TITLE
Refer from Scirius to Evebox

### ISSUE THREAD

**Issue by beyefendi** [StamusNetworks/scirius#76]
Hi,

It is very good to access the related logs from Scirius to Kibana.
Likewise, it will be very good to refer related Evebox logs from Scirius.

An illustration is attached

![istek](https://cloud.githubusercontent.com/assets/7609852/17367502/cbf94390-5998-11e6-84fa-e1d8196116b8.png)

**Comment by beyefendi** [comment]
@pevma @regit 
What do you think about that?

**Comment by pevma** [comment]
I think it is a good idea. The implementation needs to be thought through though in my view - since Scirius is not only used in SELKS where EveBox is installed but also as a stand alone management as well.

**Comment by regit** [comment]
Just added link to events list in evebox. I will push code later today and it will be part of next release.
