### ISSUE TITLE
Log-forward Suricata EVE into a SELKS CE 3.0

### ISSUE THREAD

**Issue by norandom** [StamusNetworks/scirius#77]
Hey,

I'd like to test log-forwarding Suricata EVE JSON logs into a SELKS CE installation to see if / how to cope with high data rate log input. If I am not entirely mistaken Logstash is used to stream the data into Elasticsearch in the current release. The type is "SELKS", according to the unmodified config.

Is there a handy way to change the Logstash config to archive this? A local Suricata daemon is not really useful for tests, because it will only receive a fraction of the traffic and the logs.

Best,
Marius

**Comment by regit** [comment]
Hello,

So it seems you want one suricata to send logs to a SELKS CE installation. To do that what on the easiest way is to activate beats input on logstash in SELKS  (https://www.elastic.co/guide/en/logstash/current/plugins-inputs-beats.html) and to install filebeat (https://www.elastic.co/products/beats/filebeat) on the machine running suricata to send the eve.json file.

Logstash config on SELKS should be `/etc/logstash/conf.d/logstash.conf`
