### ISSUE TITLE
Reset failed: Please make sure Kibana dashboards are installed at /opt/kibana-dashboards/: no index-pattern found

### ISSUE THREAD

**Issue by Eagleman7** [StamusNetworks/scirius#79]
When using the Reset SN dashboards button in System Settings > Kibana and after placing the KTS dashboards in /opt/kibana-dashboards/ I am getting the following error: 

Reset failed: Please make sure Kibana dashboards are installed at /opt/kibana-dashboards/: no index-pattern found

Before I placed the KTS dashboards in /opt/kibana-dashboards/ I got this error:

Reset failed: Please make sure Kibana dashboards are installed at /opt/kibana-dashboards/

**Comment by pevma** [comment]
Did you try reload?

**Comment by Eagleman7** [comment]
I did reboot the server, also forced refreshed my browser, but still the same error.

**Comment by Eagleman7** [comment]
Solved by setting the path to the KTS folder in the local_settings.py: KIBANA_DASHBOARDS_PATH = "/opt/KTS/"
