### ISSUE TITLE
Unable to import user dashboards from system settings when no dashboards exists

### ISSUE THREAD

**Issue by Eagleman7** [StamusNetworks/scirius#86]
When making a backup of user dashboards (Export user dashboards) it includes visualizations, searches and dashboards, however once you export the user dashboards, and you don't have a custom dashboard, but only the visualizations, you are not able to import the zip:

Import failed: Archive does not appear to contain dashboards

**Comment by regit** [comment]
It should be fixed by ffcecc531d33f0987e5a5d0154ad8860c4839c80
