### ISSUE TITLE
Graphs not loading when using remote ELK stack

### ISSUE THREAD

**Issue by Eagleman7** [StamusNetworks/scirius#89]
When using a remote ELK stack it cant seem to load any of the graphs, I made sure the Suricata config had the same config as the one used in SELKS. However it only seems to load the rules activity table:

http://i.imgur.com/nhsoIe5.png

This is my local_settings.py, the DNS names are resolvable:

http://lpaste.net/2826302009362087936

**Comment by pevma** [comment]
Would there be any difference if you adjust -   

> ALLOWED_HOSTS = ["*"]

**Comment by Eagleman7** [comment]
No luck with setting: ALLOWED_HOSTS = ["*"]

**Comment by pevma** [comment]
I trust you restarted Scirius :) after the adjustment ?

**Comment by Eagleman7** [comment]
I rebooted the machine.

**Comment by pevma** [comment]
What is the versions of your ELK stack components ?

**Comment by Eagleman7** [comment]
Package elasticsearch-2.4.3-1.noarch already installed and latest version
Package 1:logstash-2.4.1-1.noarch already installed and latest version
Package kibana-4.5.4-1.x86_64 already installed and latest version

**Comment by Eagleman7** [comment]
Found the issue:

Please note, that the name of the Suricata (set during edition of the object) must be equal to the host key present in Elasticsearch events. It can also be edited here: scirius -> suricata -> edit.

The host was set to the right name, but it was parsing the even.json file over a NFS share (from the ELK VM), so the host was set to elk.corp.example.com.

After changing the name of suricata in scirius to the name of my elk stack vm, it worked.
