### ISSUE TITLE
global name 'CategoryTransformForm' is not defined

### ISSUE THREAD

**Issue by Eagleman7** [StamusNetworks/scirius#91]
When clicking transform on a  category I am getting:

NameError at /rules/category/2/transform
global name 'CategoryTransformForm' is not defined
Request Method:	GET
Request URL:	http://ips.corp.example.com:8000/rules/category/2/transform
Django Version:	1.8.17
Exception Type:	NameError
Exception Value:	
global name 'CategoryTransformForm' is not defined
Exception Location:	/opt/scirius/rules/views.py in transform_category, line 483
Python Executable:	/bin/python
Python Version:	2.7.5
Python Path:	
['/usr/lib/python2.7/site-packages/git/ext/gitdb',
 '/opt/scirius',
 '/usr/lib64/python27.zip',
 '/usr/lib64/python2.7',
 '/usr/lib64/python2.7/plat-linux2',
 '/usr/lib64/python2.7/lib-tk',
 '/usr/lib64/python2.7/lib-old',
 '/usr/lib64/python2.7/lib-dynload',
 '/usr/lib64/python2.7/site-packages',
 '/usr/lib64/python2.7/site-packages/gtk-2.0',
 '/usr/lib/python2.7/site-packages',
 '/usr/lib64/python2.7/site-packages/gitdb/ext/smmap']
Server time:	Wed, 11 Jan 2017 21:00:25 +0100

This is with the latest pull.

**Comment by regit** [comment]
This hould be fied by 08a11d9172461ba7e24c879aa25eb6bfb9c718ac
