### ISSUE TITLE
Disabling rules

### ISSUE THREAD

**Issue by VN1977** [StamusNetworks/scirius#95]
Hello!
I need to disable a rule, for example 2200078. I click the link Disable rule, put a tick on Default SELKS ruleset, press Disable. I see that this rule is disabled in the list of Disabled rules. But later I get new alerts from this rule. I tried to supress it, but the same result. What do I do wrong? How to completely disable the rule?

**Comment by regit** [comment]
Modifications are not applied when you click. You need to propagate them. To do so, you need to click on Suricata in top menu,  then "ruleset actions", then at least select build and push and submit.

**Comment by VN1977** [comment]
Thanks! It works.
